import { CalendarDay, Employee, Equipment, EquipmentBlock, ProductionTask, RouteOperation, ShiftDefinition } from '../types';

export interface DispatchBoardOptions {
  tasks: ProductionTask[];
  employees: Employee[];
  equipment: Equipment[];
  shifts: ShiftDefinition[];
  calendar: CalendarDay[];
  equipmentBlocks: EquipmentBlock[];
  operations: RouteOperation[];
  onMove: (taskId: string, deltaMinutes: number) => void | Promise<void>;
  onAssignEmployee: (taskId: string, employeeId: string) => void | Promise<void>;
  onAssignEquipment: (taskId: string, equipmentId: string) => void | Promise<void>;
}

interface TaskIssue {
  kind: 'RESOURCE' | 'CALENDAR' | 'MAINTENANCE' | 'QUALIFICATION' | 'EQUIPMENT';
  message: string;
}

const MINUTE_MS = 60_000;
function dayKey(value: string | number): string { return new Date(value).toISOString().slice(0, 10); }
function overlaps(aStart: number, aEnd: number, bStart: number, bEnd: number): boolean { return aStart < bEnd && bStart < aEnd; }
function findShift(taskStart: number, shifts: ShiftDefinition[], calendar: CalendarDay[]): ShiftDefinition | undefined { const date = calendar.find(d => d.date === dayKey(taskStart)); if (!date) return undefined; const taskDate = new Date(taskStart); const dayStart = Date.UTC(taskDate.getUTCFullYear(), taskDate.getUTCMonth(), taskDate.getUTCDate()); for (const id of date.shiftIds) { const shift = shifts.find(s => s.id === id); if (!shift) continue; const start = dayStart + shift.startMinute * MINUTE_MS; const end = start + shift.durationMinutes * MINUTE_MS; if (taskStart >= start && taskStart < end) return shift; } return undefined; }
function issuesFor(task: ProductionTask, tasks: ProductionTask[], calendar: CalendarDay[], equipmentBlocks: EquipmentBlock[], shifts: ShiftDefinition[], operation: RouteOperation | undefined, employees: Employee[] = [], equipment: Equipment[] = []): TaskIssue[] { const issues: TaskIssue[] = []; const start = new Date(task.plannedStart).getTime(); const end = new Date(task.plannedEnd).getTime(); const day = calendar.find(d => d.date === dayKey(start)); if (!day?.isWorking) issues.push({ kind: 'CALENDAR', message: 'Начало задания приходится на нерабочий день.' }); if (day?.isWorking && !findShift(start, shifts, calendar)) issues.push({ kind: 'CALENDAR', message: 'Задание начинается вне назначенной рабочей смены.' }); const assignedEmployee = employees.find(e => e.id === task.assignedEmployeeIds[0]); if (operation?.requiredQualification !== undefined) { if (!assignedEmployee) issues.push({ kind: 'QUALIFICATION', message: `Требуется квалификация ${operation.requiredQualification}; сотрудник не назначен.` }); else if (assignedEmployee.qualificationLevel < operation.requiredQualification) issues.push({ kind: 'QUALIFICATION', message: `Квалификация сотрудника (${assignedEmployee.qualificationLevel}) ниже требуемой (${operation.requiredQualification}).` }); } const assignedEquipment = equipment.find(e => e.id === task.assignedEquipmentIds[0]); if (!assignedEquipment) issues.push({ kind: 'EQUIPMENT', message: 'Оборудование не назначено.' }); if (operation?.requiredEquipmentIds?.length && task.assignedEquipmentIds[0] && !operation.requiredEquipmentIds.includes(task.assignedEquipmentIds[0])) issues.push({ kind: 'EQUIPMENT', message: 'Назначенное оборудование не соответствует операции.' }); if (operation && !operation.requiredEquipmentIds?.length && assignedEquipment && assignedEquipment.workCenter !== operation.workCenter) issues.push({ kind: 'EQUIPMENT', message: 'У оборудования другой производственный участок.' }); for (const other of tasks) { if (other.id === task.id) continue; const otherStart = new Date(other.plannedStart).getTime(); const otherEnd = new Date(other.plannedEnd).getTime(); if (!overlaps(start, end, otherStart, otherEnd)) continue; if (task.assignedEmployeeIds.some(id => other.assignedEmployeeIds.includes(id))) issues.push({ kind: 'RESOURCE', message: 'Сотрудник одновременно назначен на другое задание.' }); if (task.assignedEquipmentIds.some(id => other.assignedEquipmentIds.includes(id))) issues.push({ kind: 'RESOURCE', message: 'Оборудование одновременно используется другим заданием.' }); } for (const block of equipmentBlocks) { if (!task.assignedEquipmentIds.includes(block.equipmentId)) continue; const blockStart = new Date(block.start).getTime(); const blockEnd = new Date(block.end).getTime(); if (overlaps(start, end, blockStart, blockEnd)) issues.push({ kind: 'MAINTENANCE', message: `Пересечение с блокировкой оборудования: ${block.reason}.` }); } return issues; }
function formatTime(value: string): string { return new Date(value).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' }); }
function formatDate(value: string): string { return new Date(`${value}T00:00:00.000Z`).toLocaleDateString('ru-RU', { weekday: 'short', day: '2-digit', month: '2-digit' }); }
export function renderDispatchBoard(options: DispatchBoardOptions): string { const { tasks, employees, equipment, shifts, calendar, equipmentBlocks, operations } = options; const cells = calendar.map(day => { const shiftLabels = day.shiftIds.map(id => shifts.find(s => s.id === id)?.name ?? id).join(' / '); const dayTasks = tasks.filter(task => dayKey(task.plannedStart) === day.date); return `<div class="dispatch-day ${day.isWorking ? '' : 'off'}"><div class="dispatch-day-head"><strong>${formatDate(day.date)}</strong><span>${day.isWorking ? shiftLabels : 'Выходной'}</span></div><div class="dispatch-cell">${dayTasks.length ? dayTasks.map(task => renderTaskCard(task, tasks, employees, equipment, shifts, calendar, equipmentBlocks, operations)).join('') : '<div class="empty-cell">Нет заданий</div>'}</div></div>`; }).join(''); return `<div class="dispatch-toolbar"><div><strong>Диспетчерская доска</strong><span>${calendar.length} дней · ${tasks.length} заданий</span></div><div class="legend"><span><i class="dot normal"></i>Норма</span><span><i class="dot conflict-dot"></i>Конфликт</span></div></div><div class="dispatch-grid">${cells}</div>`; }
function renderTaskCard(task: ProductionTask, tasks: ProductionTask[], employees: Employee[], equipment: Equipment[], shifts: ShiftDefinition[], calendar: CalendarDay[], equipmentBlocks: EquipmentBlock[], operations: RouteOperation[]): string { const operation = operations.find(op => op.id === task.operationId); const issues = issuesFor(task, tasks, calendar, equipmentBlocks, shifts, operation, employees, equipment); const employeeId = task.assignedEmployeeIds[0] ?? ''; const equipmentId = task.assignedEquipmentIds[0] ?? ''; const employee = employees.find(e => e.id === employeeId); const machine = equipment.find(e => e.id === equipmentId); const shift = findShift(new Date(task.plannedStart).getTime(), shifts, calendar); const duration = Math.max(1, Math.round((new Date(task.plannedEnd).getTime() - new Date(task.plannedStart).getTime()) / MINUTE_MS)); const conflictHtml = issues.length ? `<div class="task-issues">${issues.map(issue => `<div>⚠ ${issue.message}</div>`).join('')}</div>` : ''; const requiredQualification = operation?.requiredQualification ?? 0; const employeeOptions = employees.filter(e => e.active && e.qualificationLevel >= requiredQualification).map(e => `<option value="${e.id}" ${e.id === employeeId ? 'selected' : ''}>${e.name} · разряд ${e.qualificationLevel}</option>`).join(''); const equipmentOptions = equipment.filter(e => e.active && (!operation?.requiredEquipmentIds?.length || operation.requiredEquipmentIds.includes(e.id)) && (!operation?.requiredEquipmentIds?.length ? e.workCenter === operation?.workCenter : true)).map(e => `<option value="${e.id}" ${e.id === equipmentId ? 'selected' : ''}>${e.name}</option>`).join(''); return `<article class="task-card ${issues.length ? 'has-conflict' : ''}"><div class="task-card-top"><strong>${task.id}</strong><span>${shift?.name ?? 'вне смены'}</span></div><div class="task-card-title">${formatTime(task.plannedStart)}–${formatTime(task.plannedEnd)} · ${duration} мин</div><div class="task-card-meta">${employee?.name ?? 'Сотрудник не назначен'} · ${machine?.name ?? 'Оборудование не назначено'}</div><div class="task-controls"><button class="tiny" data-move="${task.id}" data-delta="-30">−30м</button><button class="tiny" data-move="${task.id}" data-delta="30">+30м</button><select data-employee="${task.id}" data-version="${task.version}" aria-label="Сотрудник"><option value="">Сотрудник</option>${employeeOptions}</select><select data-equipment="${task.id}" data-version="${task.version}" aria-label="Оборудование"><option value="">Оборудование</option>${equipmentOptions}</select></div>${conflictHtml}</article>`; }

export function bindDispatchBoard(root: HTMLElement, options: DispatchBoardOptions): void {
  root.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(button => {
    button.addEventListener('click', () => {
      const taskId = button.dataset.move;
      const delta = Number(button.dataset.delta);
      if (!taskId || !Number.isFinite(delta)) return;
      void Promise.resolve(options.onMove(taskId, delta)).catch(() => undefined);
    });
  });
  root.querySelectorAll<HTMLSelectElement>('[data-employee]').forEach(select => {
    select.addEventListener('change', () => { void Promise.resolve(options.onAssignEmployee(select.dataset.employee ?? '', select.value)).catch(() => undefined); });
  });
  root.querySelectorAll<HTMLSelectElement>('[data-equipment]').forEach(select => {
    select.addEventListener('change', () => { void Promise.resolve(options.onAssignEquipment(select.dataset.equipment ?? '', select.value)).catch(() => undefined); });
  });
}
