import type { SupabaseClient } from '@supabase/supabase-js';
import * as XLSX from 'xlsx';
import { BootstrapPayload, BootstrapValidation, SupabaseMesMasterDataRpc } from '../integration/mesMasterDataRpc';
import { getMesAuthState } from '../integration/auth';

const t=(v:unknown)=>String(v??'').trim();
const num=(v:unknown)=>Number(String(v??'').replace(',','.'));
const yes=(v:unknown,def=true)=>{const s=t(v).toLowerCase();if(!s)return def;return ['true','1','да','yes','work','рабочий','active'].includes(s);};
const list=(v:unknown)=>t(v).split(/[;,]/).map(t).filter(Boolean);
const esc=(v:unknown)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]??c));
const date=(v:unknown)=>{if(v instanceof Date)return v.toISOString().slice(0,10);const s=t(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10);};
const minute=(v:unknown)=>{if(v instanceof Date)return v.getHours()*60+v.getMinutes();const s=t(v);const m=s.match(/^(\d{1,2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):num(v)||0;};
const rows=(book:XLSX.WorkBook,name:string)=>book.Sheets[name]?XLSX.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[name],{defval:'',raw:true}):[];
const ref=(items:Record<string,unknown>[],v:unknown)=>{const x=t(v);const hit=items.find(r=>t(r.external_id||r.code||r.id)===x);return hit?t(hit.external_id||hit.code||hit.id):x;};

function parseWorkbook(buffer:ArrayBuffer):{payload:BootstrapPayload;counts:Record<string,number>;warnings:string[]}{
 const b=XLSX.read(buffer,{type:'array',cellDates:true});
 const products=rows(b,'01_Products').filter(r=>t(r.external_id||r.code||r.id));
 const professions=rows(b,'02_Professions').filter(r=>t(r.external_id||r.code||r.id));
 const qualifications=rows(b,'03_Qualifications').filter(r=>t(r.external_id||r.code||r.id));
 const employees=rows(b,'04_Employees').filter(r=>t(r.external_id||r.personnel_no||r.id));
 const employeeQualifications=rows(b,'05_Employee_Qualifications').filter(r=>t(r.employee_external_id)&&t(r.qualification_external_id));
 const workCenters=rows(b,'06_Work_Centers').filter(r=>t(r.external_id||r.code||r.id));
 const equipment=rows(b,'07_Equipment').filter(r=>t(r.external_id||r.code||r.id));
 const capabilities=rows(b,'08_Equipment_Capabilities').filter(r=>t(r.equipment_external_id)&&t(r.route_operation_code));
 const brigades=rows(b,'09_Brigades').filter(r=>t(r.external_id||r.code||r.id));
 const shifts=rows(b,'10_Shifts').filter(r=>t(r.external_id||r.code||r.id));
 const calendar=rows(b,'11_Calendars').filter(r=>t(r.date));
 const routes=rows(b,'12_Routes').filter(r=>t(r.external_id||r.code||r.id));
 const ops=rows(b,'13_Route_Operations').filter(r=>t(r.operation_external_id));
 const downtime=rows(b,'14_Downtime_Reasons').filter(r=>t(r.code));
 const scrap=rows(b,'15_Scrap_Reasons').filter(r=>t(r.code));
 const employeeSchedules=rows(b,'16_Employee_Schedules').filter(r=>t(r.employee_external_id)&&t(r.date));
 const productRef=(v:unknown)=>ref(products,v), workCenterRef=(v:unknown)=>ref(workCenters,v), shiftRef=(v:unknown)=>ref(shifts,v), qualificationRef=(v:unknown)=>ref(qualifications,v), professionRef=(v:unknown)=>ref(professions,v), brigadeRef=(v:unknown)=>ref(brigades,v), equipmentRef=(v:unknown)=>ref(equipment,v);
 const payload:BootstrapPayload={
  products:products.map(r=>({id:t(r.external_id||r.code||r.id),code:t(r.code||r.external_id||r.id),name:t(r.name),unit:t(r.unit),external_id:t(r.external_id)||null})),
  professions:professions.map(r=>({id:t(r.external_id||r.code||r.id),external_id:t(r.external_id)||null,code:t(r.code||r.external_id||r.id),name:t(r.name),description:t(r.description)||null,active:yes(r.status)})),
  qualification_levels:qualifications.map(r=>({id:t(r.external_id||r.code||r.id),external_id:t(r.external_id)||null,code:t(r.code||r.external_id||r.id),name:t(r.name),level:num(r.level)||0,description:t(r.description)||null,active:yes(r.status)})),
  brigades:brigades.map(r=>({id:t(r.external_id||r.code||r.id),external_id:t(r.external_id)||null,code:t(r.code||r.external_id||r.id),name:t(r.name),description:t(r.description)||null,active:yes(r.status)})),
  employees:employees.map(r=>({id:t(r.external_id||r.personnel_no||r.id),personnel_no:t(r.personnel_no||r.external_id||r.id),name:[t(r.last_name),t(r.first_name),t(r.middle_name)].filter(Boolean).join(' ')||t(r.name),profession:t(r.profession_external_id||r.profession),profession_id:t(r.profession_external_id)?professionRef(r.profession_external_id):null,brigade_id:t(r.brigade_external_id)?brigadeRef(r.brigade_external_id):null,qualification_id:t(r.qualification_external_id)?qualificationRef(r.qualification_external_id):null,qualification_level:num(r.qualification_level)||0,active:yes(r.status)})),
  employee_qualifications:employeeQualifications.map(r=>({employee_id:t(r.employee_external_id),qualification_id:qualificationRef(r.qualification_external_id),valid_from:date(r.valid_from)||null,valid_to:date(r.valid_to)||null,is_primary:yes(r.is_primary,false),notes:t(r.notes)||null})),
  work_centers:workCenters.map(r=>({id:t(r.external_id||r.code||r.id),external_id:t(r.external_id)||null,code:t(r.code||r.external_id||r.id),name:t(r.name),site_code:t(r.site_code)||null,description:t(r.description)||null,active:yes(r.status)})),
  equipment:equipment.map(r=>({id:t(r.external_id||r.code||r.id),code:t(r.code||r.external_id||r.id),name:t(r.name),work_center:workCenterRef(r.work_center_external_id||r.work_center),capabilities:list(r.capabilities),active:yes(r.status)})),
  equipment_capabilities:capabilities.map(r=>({equipment_id:equipmentRef(r.equipment_external_id),operation_code:t(r.route_operation_code),capability_level:t(r.capability_level)||'FULL',valid_from:date(r.valid_from)||null,valid_to:date(r.valid_to)||null,notes:t(r.notes)||null})),
  routes:routes.map(r=>({id:t(r.external_id||r.code||r.id),external_id:t(r.external_id)||null,product_id:productRef(r.product_external_id||r.product_id),code:t(r.code||r.external_id||r.id),name:t(r.name),version:num(r.version)||1,active:yes(r.is_active??r.active??r.status,true),valid_from:date(r.valid_from)||null,valid_to:date(r.valid_to)||null,description:t(r.description)||null})),
  shifts:shifts.map(r=>({id:t(r.external_id||r.code||r.id),name:t(r.name||r.code),start_minute:minute(r.start_time),duration_minutes:num(r.duration_hours)*60||((minute(r.end_time)-minute(r.start_time)+1440)%1440||1440),active:yes(r.status)})),
  route_operations:ops.map(r=>({id:t(r.operation_external_id),product_id:productRef(r.product_external_id||r.product_id||r.route_external_id?.toString().replace(/^ROUTE-/,'PROD-')),route_id:t(r.route_external_id)||undefined,sequence:num(r.sequence_no),code:t(r.operation_code||r.operation_external_id),name:t(r.operation_name),work_center:workCenterRef(r.work_center_external_id||r.work_center),required_qualification:t(r.qualification_external_id)?num(r.qualification_external_id):undefined,required_qualification_id:t(r.qualification_external_id)?qualificationRef(r.qualification_external_id):undefined,required_equipment_ids:list(r.equipment_external_id||r.required_equipment_ids).map(equipmentRef),setup_norm_hours:num(r.setup_norm_hours||r.setup_hours),labor_norm_hours_per_unit:num(r.labor_norm_hours_per_unit||r.labor_norm),workers_required:num(r.workers_required)||1,active:yes(r.status)})),
  calendar_days:calendar.map(r=>({date:date(r.date),is_working:yes(r.is_working,false),shift_ids:list(r.shift_external_id).map(shiftRef)})).filter(r=>r.date),
  employee_schedules:employeeSchedules.map(r=>({employee_id:t(r.employee_external_id),date:date(r.date),shift_ids:list(r.shift_external_id).map(shiftRef),status:t(r.status)||'WORK'})).filter(r=>r.employee_id&&r.date),
  downtime_reasons:downtime.map(r=>({code:t(r.code),name:t(r.name),category:t(r.category)||'OTHER',is_planned:yes(r.is_planned,false),description:t(r.description)||null,active:yes(r.status)})),
  scrap_reasons:scrap.map(r=>({code:t(r.code),name:t(r.name),category:t(r.category)||'OTHER',description:t(r.description)||null,active:yes(r.status)}))
 };
 const warnings:string[]=[];
 if(capabilities.length===0)warnings.push('Лист 08_Equipment_Capabilities пуст — связи оборудования с операциями не будут импортированы.');
 if(routes.length===0)warnings.push('Лист 12_Routes пуст — заголовки маршрутов отсутствуют.');
 return {payload,counts:{products:payload.products?.length||0,professions:payload.professions?.length||0,qualification_levels:payload.qualification_levels?.length||0,brigades:payload.brigades?.length||0,employees:payload.employees?.length||0,employee_qualifications:payload.employee_qualifications?.length||0,work_centers:payload.work_centers?.length||0,equipment:payload.equipment?.length||0,equipment_capabilities:payload.equipment_capabilities?.length||0,routes:payload.routes?.length||0,route_operations:payload.route_operations?.length||0,shifts:payload.shifts?.length||0,calendar_days:payload.calendar_days?.length||0,employee_schedules:payload.employee_schedules?.length||0,downtime_reasons:payload.downtime_reasons?.length||0,scrap_reasons:payload.scrap_reasons?.length||0},warnings};
}

export async function mountImportCenterPage(root:HTMLElement,client:SupabaseClient):Promise<void>{
 const auth=await getMesAuthState(client);if(!auth.identity)return;
 const host=document.createElement('section');host.className='panel';root.querySelector('main.page')?.appendChild(host);
 host.innerHTML='<div class="panel-head"><div><h2>Центр импорта НСИ</h2><div class="subtle">Excel → разбор → серверная проверка → подтверждение → атомарная загрузка</div></div><button class="primary" id="mes-import-refresh">Обновить историю</button></div><div style="padding:16px 18px;border-bottom:1px solid #e2e8f0"><input id="mes-import-file" type="file" accept=".xlsx,.xls"/><div id="mes-import-preview" class="subtle" style="margin-top:10px">Выберите заполненный Excel-шаблон.</div></div><div id="mes-import-actions" style="padding:14px 18px;display:flex;gap:10px;align-items:center;border-bottom:1px solid #e2e8f0"></div><div style="padding:14px 18px"><div class="section-title">История импорта</div><div class="table-wrap"><table><thead><tr><th>Время</th><th>Источник</th><th>Статус</th><th>Результат</th></tr></thead><tbody id="mes-import-history"><tr><td colspan="4">Загрузка…</td></tr></tbody></table></div></div>';
 const preview=host.querySelector<HTMLDivElement>('#mes-import-preview')!;const actions=host.querySelector<HTMLDivElement>('#mes-import-actions')!;const history=host.querySelector<HTMLTableSectionElement>('#mes-import-history')!;const rpc=new SupabaseMesMasterDataRpc(client);let parsed:{payload:BootstrapPayload;counts:Record<string,number>;warnings:string[]}|null=null;let validated=false;
 const loadHistory=async()=>{const{data,error}=await client.from('mes_master_import_runs').select('id,actor_id,started_at,finished_at,status,source_name,counts,errors').order('started_at',{ascending:false}).limit(20);if(error){history.innerHTML='<tr><td colspan="4">'+esc(error.message)+'</td></tr>';return;}history.innerHTML=(data??[]).map((r:any)=>'<tr><td>'+new Date(r.started_at).toLocaleString('ru-RU')+'</td><td>'+esc(r.source_name||'—')+'</td><td>'+esc(r.status)+'</td><td><code>'+esc(JSON.stringify(r.counts||r.errors||{}))+'</code></td></tr>').join('')||'<tr><td colspan="4">История пока пуста</td></tr>';};
 host.querySelector<HTMLButtonElement>('#mes-import-refresh')!.addEventListener('click',()=>void loadHistory());
 host.querySelector<HTMLInputElement>('#mes-import-file')!.addEventListener('change',async()=>{const file=host.querySelector<HTMLInputElement>('#mes-import-file')!.files?.[0];if(!file)return;parsed=null;validated=false;actions.innerHTML='';try{parsed=parseWorkbook(await file.arrayBuffer());const validation=await rpc.validateBootstrap(parsed.payload);validated=validation.valid;preview.innerHTML='<strong>'+esc(file.name)+'</strong><br>'+Object.entries(parsed.counts).map(([k,v])=>esc(k)+': '+v).join(' · ')+(parsed.warnings.length?'<br><br><strong>Предупреждения Excel:</strong><br>'+parsed.warnings.map(esc).join('<br>'):'')+'<div id="mes-import-validation" style="margin-top:8px">'+(validation.errors.length?'<strong>Ошибки:</strong><br>'+validation.errors.map(esc).join('<br>'):'<strong>Серверная проверка пройдена.</strong>')+(validation.warnings.length?'<br><br><strong>Предупреждения сервера:</strong><br>'+validation.warnings.map(esc).join('<br>'):'')+'</div>';actions.innerHTML=validated?'<button class="primary" id="mes-import-confirm">Подтвердить и импортировать</button>':'<span class="status-pill status-danger">Импорт заблокирован</span>';if(validated)host.querySelector<HTMLButtonElement>('#mes-import-confirm')!.addEventListener('click',async()=>{if(!parsed||!validated)return;const btn=host.querySelector<HTMLButtonElement>('#mes-import-confirm')!;btn.disabled=true;try{const result=await rpc.importBootstrap(file.name,parsed.payload);preview.innerHTML+='<div style="margin-top:10px;color:#166534"><strong>Импорт завершён.</strong> Run: '+esc(result.runId||'—')+'<br>'+esc(JSON.stringify(result.counts||{}))+'</div>';actions.innerHTML='<span class="status-pill status-ok">COMPLETED</span>';await loadHistory();}catch(e){preview.innerHTML+='<div style="margin-top:10px;color:#991b1b"><strong>Импорт не выполнен:</strong> '+esc(e instanceof Error?e.message:'ошибка')+'</div>';btn.disabled=false;}});}catch(e){preview.innerHTML='<span style="color:#b91c1c">Не удалось прочитать/проверить Excel: '+esc(e instanceof Error?e.message:'ошибка')+'</span>';}});
 await loadHistory();
}
