import type { SupabaseClient } from '@supabase/supabase-js';
import { getMesAuthState } from '../integration/auth';
import { SupabaseMesMasterDataRpc, MasterProduct, MasterEmployee, MasterEquipment, MasterShift } from '../integration/mesMasterDataRpc';

const esc=(v:unknown)=>String(v??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]??ch));
const minToTime=(m:number)=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const timeToMin=(s:string)=>{const [h,m]=s.split(':').map(Number);return (Number.isFinite(h)?h:0)*60+(Number.isFinite(m)?m:0);};

export async function mountMasterDataPage(root:HTMLElement,client:SupabaseClient):Promise<void>{
  const auth=await getMesAuthState(client); if(!auth.identity)return;
  const host=document.createElement('section'); host.className='panel'; root.querySelector('main.page')?.appendChild(host);
  const rpc=new SupabaseMesMasterDataRpc(client); const state={tab:'products'};
  async function load(){
    const [p,e,eq,sh]=await Promise.all([
      client.from('products').select('id,code,name,unit,external_id').order('code'),
      client.from('employees').select('id,personnel_no,name,profession,qualification_level,active').order('name'),
      client.from('equipment').select('id,code,name,work_center,capabilities,active').order('code'),
      client.from('shift_definitions').select('id,name,start_minute,duration_minutes,active').order('id')
    ]);
    for(const q of [p,e,eq,sh]) if(q.error) throw q.error;
    const products=(p.data??[]) as MasterProduct[], employees=(e.data??[]) as MasterEmployee[], equipment=(eq.data??[]) as MasterEquipment[], shifts=(sh.data??[]) as MasterShift[];
    const tabs=`<div class="panel-head"><div><h2>НСИ MES</h2><div class="subtle">Хранение и редактирование основных справочников через серверные RPC · роль ${esc(auth.identity!.role)}</div></div><button class="primary" id="md-refresh">Обновить</button></div><div class="dispatch-toolbar"><div><button class="tiny" data-md-tab="products">Продукция (${products.length})</button><button class="tiny" data-md-tab="employees">Персонал (${employees.length})</button><button class="tiny" data-md-tab="equipment">Оборудование (${equipment.length})</button><button class="tiny" data-md-tab="shifts">Смены (${shifts.length})</button></div></div>`;
    let body='';
    if(state.tab==='products') body=`<div style="padding:14px 18px"><form id="md-product" class="maintenance-form"><input name="id" placeholder="ID" required><input name="code" placeholder="Код" required><input name="name" placeholder="Наименование" required><input name="unit" placeholder="Ед. изм." required><input name="external_id" placeholder="External ID"><button class="primary">Сохранить</button></form></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Код</th><th>Наименование</th><th>Ед.</th><th>External ID</th></tr></thead><tbody>${products.map(x=>`<tr><td>${esc(x.id)}</td><td><strong>${esc(x.code)}</strong></td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td>${esc(x.external_id??'')}</td></tr>`).join('')||'<tr><td colspan="5">Нет данных</td></tr>'}</tbody></table></div>`;
    if(state.tab==='employees') body=`<div style="padding:14px 18px"><form id="md-employee" class="maintenance-form"><input name="id" placeholder="ID" required><input name="personnel_no" placeholder="Табельный №" required><input name="name" placeholder="ФИО" required><input name="profession" placeholder="Профессия" required><input name="qualification_level" type="number" min="0" placeholder="Разряд" value="1" required><label style="font-size:11px"><input name="active" type="checkbox" checked> активен</label><button class="primary">Сохранить</button></form></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Таб. №</th><th>ФИО</th><th>Профессия</th><th>Разряд</th><th>Статус</th></tr></thead><tbody>${employees.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.personnel_no)}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.profession)}</td><td>${x.qualification_level}</td><td>${x.active?'Активен':'Неактивен'}</td></tr>`).join('')||'<tr><td colspan="6">Нет данных</td></tr>'}</tbody></table></div>`;
    if(state.tab==='equipment') body=`<div style="padding:14px 18px"><form id="md-equipment" class="maintenance-form"><input name="id" placeholder="ID" required><input name="code" placeholder="Код" required><input name="name" placeholder="Наименование" required><input name="work_center" placeholder="Участок" required><input name="capabilities" placeholder="Capability1,Capability2"><label style="font-size:11px"><input name="active" type="checkbox" checked> доступно</label><button class="primary">Сохранить</button></form></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Код</th><th>Оборудование</th><th>Участок</th><th>Возможности</th><th>Статус</th></tr></thead><tbody>${equipment.map(x=>`<tr><td>${esc(x.id)}</td><td><strong>${esc(x.code)}</strong></td><td>${esc(x.name)}</td><td>${esc(x.work_center)}</td><td>${esc(x.capabilities.join(', '))}</td><td>${x.active?'Доступно':'Недоступно'}</td></tr>`).join('')||'<tr><td colspan="6">Нет данных</td></tr>'}</tbody></table></div>`;
    if(state.tab==='shifts') body=`<div style="padding:14px 18px"><form id="md-shift" class="maintenance-form"><input name="id" placeholder="ID" required><input name="name" placeholder="Название" required><input name="start" type="time" value="08:00" required><input name="duration" type="number" min="1" max="24" step="0.5" value="12" placeholder="Часов" required><label style="font-size:11px"><input name="active" type="checkbox" checked> активна</label><button class="primary">Сохранить</button></form></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Смена</th><th>Начало</th><th>Длительность</th><th>Статус</th></tr></thead><tbody>${shifts.map(x=>`<tr><td>${esc(x.id)}</td><td><strong>${esc(x.name)}</strong></td><td>${minToTime(x.start_minute)}</td><td>${(x.duration_minutes/60).toFixed(1)} ч</td><td>${x.active?'Активна':'Неактивна'}</td></tr>`).join('')||'<tr><td colspan="5">Нет данных</td></tr>'}</tbody></table></div>`;
    host.innerHTML=tabs+body;
    host.querySelectorAll<HTMLButtonElement>('[data-md-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.mdTab??'products';void load();}));
    host.querySelector<HTMLButtonElement>('#md-refresh')?.addEventListener('click',()=>void load());
    const productForm=host.querySelector<HTMLFormElement>('#md-product');
    productForm?.addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(productForm);await rpc.saveProduct({id:String(f.get('id')||''),code:String(f.get('code')||''),name:String(f.get('name')||''),unit:String(f.get('unit')||''),external_id:String(f.get('external_id')||'')||null});await load();});
    const employeeForm=host.querySelector<HTMLFormElement>('#md-employee');
    employeeForm?.addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(employeeForm);await rpc.saveEmployee({id:String(f.get('id')||''),personnel_no:String(f.get('personnel_no')||''),name:String(f.get('name')||''),profession:String(f.get('profession')||''),qualification_level:Number(f.get('qualification_level')||0),active:f.get('active')==='on'});await load();});
    const equipmentForm=host.querySelector<HTMLFormElement>('#md-equipment');
    equipmentForm?.addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(equipmentForm);await rpc.saveEquipment({id:String(f.get('id')||''),code:String(f.get('code')||''),name:String(f.get('name')||''),work_center:String(f.get('work_center')||''),capabilities:String(f.get('capabilities')||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean),active:f.get('active')==='on'});await load();});
    const shiftForm=host.querySelector<HTMLFormElement>('#md-shift');
    shiftForm?.addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(shiftForm);await rpc.saveShift({id:String(f.get('id')||''),name:String(f.get('name')||''),start_minute:timeToMin(String(f.get('start')||'00:00')),duration_minutes:Math.round(Number(f.get('duration')||12)*60),active:f.get('active')==='on'});await load();});
  }
  try{await load();}catch(e){host.innerHTML=`<div class="panel-head"><div><h2>НСИ MES</h2><div class="subtle" style="color:#b91c1c">${esc(e instanceof Error?e.message:'Не удалось загрузить НСИ')}</div></div></div>`;}
}