import type { SupabaseClient } from '@supabase/supabase-js';
import { getMesAuthState } from '../integration/auth';
import { SupabaseMesMasterDataRpc } from '../integration/mesMasterDataRpc';
import './nsiWorkspacePage.css';
const esc=(v:unknown)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]??c));
const uid=()=>crypto.randomUUID(); const st=(v:boolean)=>`<span class="nsi-status ${v?'ok':'off'}">${v?'Активен':'Неактивен'}</span>`;
export async function mountNsiWorkspacePage(root:HTMLElement,client:SupabaseClient):Promise<void>{
 const auth=await getMesAuthState(client);if(!auth.identity)return; const host=document.createElement('section');host.className='panel nsi-workspace-page';root.querySelector('main.page')?.appendChild(host);const rpc=new SupabaseMesMasterDataRpc(client);
 const s={tab:'overview',q:'',open:null as string|null};
 async function load(){
  const [p,e,eq,wc,r,o,pr,ql,br]=await Promise.all([
   client.from('products').select('id,code,name,unit,external_id').order('code'),client.from('employees').select('id,personnel_no,name,profession,profession_id,brigade_id,qualification_id,qualification_level,active').order('name'),client.from('equipment').select('id,code,name,work_center,work_center_id,capabilities,active').order('code'),client.from('work_centers').select('id,code,name,site_code,description,active').order('code'),client.from('routes').select('id,product_id,code,name,version,active,valid_from,valid_to').order('code').order('version'),client.from('route_operations').select('id,route_id,product_id,sequence,code,name,work_center,work_center_id,required_qualification,required_qualification_id,required_equipment_ids,labor_norm_hours_per_unit,setup_norm_hours,workers_required,active').order('route_id').order('sequence'),client.from('professions').select('id,code,name,active').order('code'),client.from('qualification_levels').select('id,code,name,level,active').order('level').order('code'),client.from('brigades').select('id,code,name,active').order('code')]);
  for(const x of [p,e,eq,wc,r,o,pr,ql,br])if(x.error)throw x.error; const d:any={products:p.data??[],employees:e.data??[],equipment:eq.data??[],workCenters:wc.data??[],routes:r.data??[],operations:o.data??[],professions:pr.data??[],qualifications:ql.data??[],brigades:br.data??[]};
  const q=s.q.toLowerCase(),match=(...v:unknown[])=>!q||v.join(' ').toLowerCase().includes(q),pmap=new Map(d.products.map((x:any)=>[x.id,x])),wcmap=new Map(d.workCenters.map((x:any)=>[x.id,x])),qmap=new Map(d.qualifications.map((x:any)=>[x.id,x]));
  const nav=[['overview','Обзор'],['products','Номенклатура'],['routes','Технологии'],['equipment','Оборудование'],['employees','Персонал'],['organization','Организация'],['references','Справочники']]; let body='';
  if(s.tab==='overview')body=`<div class="nsi-kpis">${[['products','Номенклатура',d.products.length],['routes','Маршруты',d.routes.length],['equipment','Оборудование',d.equipment.length],['employees','Сотрудники',d.employees.length]].map(x=>`<button data-tab="${x[0]}"><strong>${x[2]}</strong><span>${x[1]}</span></button>`).join('')}</div><div class="nsi-grid-two"><div class="nsi-card"><div class="nsi-card-title">Готовность НСИ</div>${[['Номенклатура',d.products.length],['Рабочие центры',d.workCenters.length],['Оборудование',d.equipment.length],['Персонал',d.employees.length],['Маршруты',d.routes.length]].map(x=>`<div class="nsi-check">${x[1]?'✓':'○'} ${x[0]} <span>${x[1]}</span></div>`).join('')}<div class="nsi-note">Демо-данные не подставляются. Production НСИ заводится вручную или через Import Center.</div></div><div class="nsi-card"><div class="nsi-card-title">Источники</div><div class="nsi-owner"><b>ERP / Workforce</b><span>Номенклатура</span></div><div class="nsi-owner"><b>MES</b><span>Маршруты, оборудование, рабочие центры, персонал</span></div><div class="nsi-owner"><b>ADMIN</b><span>Доступ и контроль полноты</span></div></div></div>`;
  if(s.tab==='products')body=`<div class="nsi-section-head"><div><div class="nsi-section-title">Номенклатура</div><div class="subtle">Внешний источник; в MES только просмотр</div></div><span class="nsi-readonly">Import Center</span></div><div class="table-wrap nsi-table"><table><thead><tr><th>Код</th><th>Наименование</th><th>Ед.</th><th>Источник</th><th>External ID</th></tr></thead><tbody>${d.products.filter((x:any)=>match(x.code,x.name,x.unit)).map((x:any)=>`<tr data-open="products:${x.id}"><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td><span class="nsi-source">ERP / Workforce</span></td><td>${esc(x.external_id??'—')}</td></tr>`).join('')||'<tr><td colspan="5">Нет данных</td></tr>'}</tbody></table></div>`;
  if(s.tab==='routes')body=`<div class="nsi-section-head"><div><div class="nsi-section-title">Технологии</div><div class="subtle">Маршрутная карта с последовательностью операций</div></div><button class="primary" id="new-route">Новый маршрут</button></div><div class="table-wrap nsi-table"><table><thead><tr><th>Код</th><th>Продукт</th><th>Название</th><th>Версия</th><th>Операций</th><th>Статус</th></tr></thead><tbody>${d.routes.filter((x:any)=>match(x.code,x.name,pmap.get(x.product_id)?.code)).map((x:any)=>`<tr data-open="routes:${x.id}"><td><b>${esc(x.code)}</b></td><td>${esc(pmap.get(x.product_id)?.code??x.product_id)}</td><td>${esc(x.name)}</td><td>v${x.version}</td><td>${d.operations.filter((o:any)=>o.route_id===x.id).length}</td><td>${st(x.active)}</td></tr>`).join('')||'<tr><td colspan="6">Маршруты не настроены</td></tr>'}</tbody></table></div>`;
  if(s.tab==='equipment')body=`<div class="nsi-section-head"><div><div class="nsi-section-title">Оборудование</div><div class="subtle">Рабочий центр, возможности и статус</div></div><button class="primary" id="new-equipment">Новое оборудование</button></div><div class="table-wrap nsi-table"><table><thead><tr><th>Код</th><th>Оборудование</th><th>Рабочий центр</th><th>Возможности</th><th>Статус</th></tr></thead><tbody>${d.equipment.filter((x:any)=>match(x.code,x.name,x.work_center,wcmap.get(x.work_center_id)?.name)).map((x:any)=>`<tr data-open="equipment:${x.id}"><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${esc(wcmap.get(x.work_center_id)?.code??x.work_center??'—')}</td><td>${esc((x.capabilities??[]).join(', ')||'—')}</td><td>${st(x.active)}</td></tr>`).join('')||'<tr><td colspan="5">Оборудование не заведено</td></tr>'}</tbody></table></div>`;
  if(s.tab==='employees')body=`<div class="nsi-section-head"><div><div class="nsi-section-title">Персонал</div><div class="subtle">Профессия, квалификация, бригада</div></div><button class="primary" id="new-employee">Новый сотрудник</button></div><div class="table-wrap nsi-table"><table><thead><tr><th>Таб. №</th><th>ФИО</th><th>Профессия</th><th>Квалификация</th><th>Бригада</th><th>Статус</th></tr></thead><tbody>${d.employees.filter((x:any)=>match(x.personnel_no,x.name,x.profession)).map((x:any)=>`<tr data-open="employees:${x.id}"><td><b>${esc(x.personnel_no)}</b></td><td>${esc(x.name)}</td><td>${esc(d.professions.find((p:any)=>p.id===x.profession_id)?.name??x.profession??'—')}</td><td>${esc(qmap.get(x.qualification_id)?.name??String(x.qualification_level??'—'))}</td><td>${esc(d.brigades.find((b:any)=>b.id===x.brigade_id)?.name??'—')}</td><td>${st(x.active)}</td></tr>`).join('')||'<tr><td colspan="6">Сотрудники не заведены</td></tr>'}</tbody></table></div>`;
  if(s.tab==='organization')body=`<div class="nsi-section-head"><div><div class="nsi-section-title">Организация</div><div class="subtle">Рабочие центры и площадки</div></div><button class="primary" id="new-wc">Новый рабочий центр</button></div><div class="table-wrap nsi-table"><table><thead><tr><th>Код</th><th>Рабочий центр</th><th>Площадка</th><th>Оборудование</th><th>Статус</th></tr></thead><tbody>${d.workCenters.filter((x:any)=>match(x.code,x.name,x.site_code)).map((x:any)=>`<tr data-open="work_centers:${x.id}"><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${esc(x.site_code??'—')}</td><td>${d.equipment.filter((e:any)=>e.work_center_id===x.id).length}</td><td>${st(x.active)}</td></tr>`).join('')||'<tr><td colspan="5">Рабочие центры не заведены</td></tr>'}</tbody></table></div>`;
  if(s.tab==='references')body=`<div class="nsi-reference-grid"><div><b>Профессии</b><span>${d.professions.length}</span></div><div><b>Квалификации</b><span>${d.qualifications.length}</span></div><div><b>Бригады</b><span>${d.brigades.length}</span></div><div><b>Операции</b><span>${d.operations.length}</span></div></div><div class="nsi-card"><div class="nsi-card-title">Связанные справочники</div><div class="subtle">Профессии и квалификации используются из карточек сотрудников, рабочие центры — из оборудования и маршрутов.</div></div>`;
  let drawer=''; if(s.open){const [type,key]=s.open.split(':');if(type==='routes'){const r=d.routes.find((x:any)=>x.id===key);if(r){const ops=d.operations.filter((o:any)=>o.route_id===key).sort((a:any,b:any)=>a.sequence-b.sequence);drawer=`<div class="nsi-drawer-backdrop" data-close></div><aside class="nsi-drawer"><div class="nsi-drawer-head"><div><span class="nsi-source">MES</span><h3>${esc(r.code)} · ${esc(r.name)}</h3><div class="subtle">${esc(pmap.get(r.product_id)?.name??r.product_id)} · v${r.version}</div></div><button class="tiny" data-close>Закрыть</button></div><div class="nsi-operation-chain">${ops.map((o:any)=>`<div class="nsi-operation"><div class="nsi-op-no">${o.sequence}</div><div><b>${esc(o.code)} · ${esc(o.name)}</b><div class="subtle">${esc(wcmap.get(o.work_center_id)?.name??o.work_center??'—')} · ${esc(qmap.get(o.required_qualification_id)?.name??(o.required_qualification==null?'Квалификация не задана':'разряд '+o.required_qualification))}</div><div class="nsi-op-meta">${o.labor_norm_hours_per_unit??0} н-ч/ед. · наладка ${o.setup_norm_hours??0} н-ч · ${o.workers_required??1} чел.</div></div></div>`).join('')||'<div class="nsi-empty">Операции не настроены.</div>'}</div></aside>`;}}else{const map:any={products:d.products,equipment:d.equipment,employees:d.employees,work_centers:d.workCenters};const x=map[type]?.find((z:any)=>z.id===key);if(x)drawer=`<div class="nsi-drawer-backdrop" data-close></div><aside class="nsi-drawer"><div class="nsi-drawer-head"><div><span class="nsi-source">MES</span><h3>${esc(x.code??x.personnel_no)} · ${esc(x.name)}</h3></div><button class="tiny" data-close>Закрыть</button></div><div class="nsi-detail-list">${Object.entries(x).filter(([k])=>!['id'].includes(k)).slice(0,8).map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(Array.isArray(v)?v.join(', '):v as any)}</b></div>`).join('')}</div></aside>`;}}
  host.innerHTML=`<div class="nsi-head"><div><div class="nsi-title">НСИ</div><div class="subtle">Единое рабочее пространство · ${esc(auth.identity!.role)}</div></div><button class="primary" id="refresh">Обновить</button></div><div class="nsi-nav">${nav.map(([i,l])=>`<button class="nsi-nav-item ${s.tab===i?'active':''}" data-tab="${i}">${l}</button>`).join('')}</div><div class="nsi-toolbar"><input id="search" value="${esc(s.q)}" placeholder="Поиск по коду, названию, табельному №…"><span class="subtle">Изменения через серверные RPC</span></div>${body}${drawer}`;
  host.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.addEventListener('click',()=>{s.tab=b.dataset.tab??'overview';s.open=null;void load();}));host.querySelectorAll<HTMLElement>('[data-open]').forEach(e=>e.addEventListener('click',()=>{s.open=e.dataset.open??null;void load();}));host.querySelectorAll<HTMLElement>('[data-close]').forEach(e=>e.addEventListener('click',()=>{s.open=null;void load();}));host.querySelector<HTMLButtonElement>('#refresh')?.addEventListener('click',()=>void load());host.querySelector<HTMLInputElement>('#search')?.addEventListener('input',e=>{s.q=(e.currentTarget as HTMLInputElement).value;void load();});
  host.querySelector<HTMLButtonElement>('#new-wc')?.addEventListener('click',async()=>{const code=prompt('Код рабочего центра');if(!code)return;const name=prompt('Наименование');if(!name)return;const site=prompt('Площадка')||null;try{await rpc.saveWorkCenter({id:uid(),external_id:null,code,name,site_code:site,description:null,active:true});await load();}catch(e){alert(e instanceof Error?e.message:'Не удалось сохранить');}});
  host.querySelector<HTMLButtonElement>('#new-equipment')?.addEventListener('click',async()=>{const code=prompt('Код оборудования');if(!code)return;const name=prompt('Наименование');if(!name)return;const wc=(d.workCenters as any[])[0]?.id;if(!wc){alert('Сначала заведите рабочий центр');return;}const caps=(prompt('Возможности через запятую')||'').split(',').map(x=>x.trim()).filter(Boolean);try{await rpc.saveEquipmentNormalized({id:uid(),code,name,work_center:'',work_center_id:wc,capabilities:caps,active:true});await load();}catch(e){alert(e instanceof Error?e.message:'Не удалось сохранить');}});
  host.querySelector<HTMLButtonElement>('#new-employee')?.addEventListener('click',async()=>{const personnel_no=prompt('Табельный №');if(!personnel_no)return;const name=prompt('ФИО');if(!name)return;const profession=prompt('Профессия');if(!profession)return;const qualification_level=Number(prompt('Разряд','1')||1);try{await rpc.saveEmployee({id:uid(),personnel_no,name,profession,qualification_level,active:true});await load();}catch(e){alert(e instanceof Error?e.message:'Не удалось сохранить');}});
  host.querySelector<HTMLButtonElement>('#new-route')?.addEventListener('click',async()=>{const product=(d.products as any[])[0];if(!product){alert('Сначала заведите/импортируйте номенклатуру');return;}const code=prompt('Код маршрута');if(!code)return;const name=prompt('Наименование');if(!name)return;try{await rpc.saveRoute({id:uid(),external_id:null,product_id:product.id,code,name,version:1,active:true,valid_from:null,valid_to:null,description:null});await load();}catch(e){alert(e instanceof Error?e.message:'Не удалось сохранить');}});
 }
 try{await load();}catch(e){host.innerHTML=`<div class="nsi-head"><div><div class="nsi-title">НСИ</div><div style="color:#b91c1c">${esc(e instanceof Error?e.message:'Не удалось загрузить НСИ')}</div></div></div>`;}
}
