-- Qualification-specific equipment access.
-- A qualification may authorize an employee to work only on selected equipment.
create table if not exists qualification_equipment_access (
  id bigint generated by default as identity primary key,
  qualification_id text not null references qualification_levels(id) on delete cascade,
  equipment_id text not null references equipment(id) on delete cascade,
  valid_from date,
  valid_to date,
  notes text,
  created_at timestamptz not null default now(),
  constraint qualification_equipment_access_unique unique (qualification_id, equipment_id),
  constraint qualification_equipment_access_validity check (
    valid_to is null or valid_from is null or valid_to >= valid_from
  )
);

create index if not exists idx_qualification_equipment_access_qualification
  on qualification_equipment_access(qualification_id);
create index if not exists idx_qualification_equipment_access_equipment
  on qualification_equipment_access(equipment_id);

alter table qualification_equipment_access enable row level security;
revoke all on qualification_equipment_access from anon;
grant select on qualification_equipment_access to authenticated;
drop policy if exists qualification_equipment_access_select_authenticated on qualification_equipment_access;
create policy qualification_equipment_access_select_authenticated
  on qualification_equipment_access
  for select to authenticated
  using (true);

create or replace function public.mes_master_save_qualification_equipment_access(
  p_id bigint default null,
  p_qualification_id text,
  p_equipment_id text,
  p_valid_from date default null,
  p_valid_to date default null,
  p_notes text default null
) returns qualification_equipment_access
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  r qualification_equipment_access%rowtype;
begin
  perform mes_require_master_editor();

  if not exists (
    select 1 from qualification_levels
    where id = trim(p_qualification_id) and active
  ) then
    raise exception 'Активная квалификация не найдена: %', p_qualification_id;
  end if;

  if not exists (
    select 1 from equipment
    where id = trim(p_equipment_id) and active
  ) then
    raise exception 'Активное оборудование не найдено: %', p_equipment_id;
  end if;

  if p_valid_from is not null and p_valid_to is not null and p_valid_to < p_valid_from then
    raise exception 'Дата окончания допуска не может быть раньше даты начала';
  end if;

  insert into qualification_equipment_access(
    id, qualification_id, equipment_id, valid_from, valid_to, notes
  ) values (
    p_id,
    trim(p_qualification_id),
    trim(p_equipment_id),
    p_valid_from,
    p_valid_to,
    nullif(trim(p_notes), '')
  )
  on conflict (qualification_id, equipment_id) do update set
    valid_from = excluded.valid_from,
    valid_to = excluded.valid_to,
    notes = excluded.notes
  returning * into r;

  return r;
end;
$$;

revoke all on function public.mes_master_save_qualification_equipment_access(bigint,text,text,date,date,text) from public, anon;
grant execute on function public.mes_master_save_qualification_equipment_access(bigint,text,text,date,date,text) to authenticated;

create or replace function public.mes_master_delete_qualification_equipment_access(
  p_id bigint
) returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  perform mes_require_master_editor();
  delete from qualification_equipment_access where id = p_id;
end;
$$;

revoke all on function public.mes_master_delete_qualification_equipment_access(bigint) from public, anon;
grant execute on function public.mes_master_delete_qualification_equipment_access(bigint) to authenticated;

-- Keep the existing single primary qualification field compatible with the
-- normalized employee_qualifications table used by the execution guard.
create or replace function public.mes_master_save_employee(
  p_id text,
  p_personnel_no text,
  p_name text,
  p_profession_id text,
  p_qualification_id text,
  p_brigade_id text,
  p_active boolean default true
) returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  r employees%rowtype;
  v_profession professions%rowtype;
  v_qualification qualification_levels%rowtype;
begin
  perform mes_require_master_editor();

  if nullif(trim(p_id), '') is null
     or nullif(trim(p_personnel_no), '') is null
     or nullif(trim(p_name), '') is null then
    raise exception 'ID, табельный номер и ФИО обязательны';
  end if;

  select * into v_profession
  from professions
  where id = trim(p_profession_id) and active = true;
  if not found then
    raise exception 'Выберите активную профессию из справочника';
  end if;

  if nullif(trim(p_qualification_id), '') is not null then
    select * into v_qualification
    from qualification_levels
    where id = trim(p_qualification_id) and active = true;
    if not found then
      raise exception 'Выбрана недействующая квалификация';
    end if;
  end if;

  if nullif(trim(p_brigade_id), '') is not null
     and not exists(
       select 1 from brigades
       where id = trim(p_brigade_id) and active = true
     ) then
    raise exception 'Выбрана недействующая бригада';
  end if;

  insert into employees(
    id, personnel_no, name, profession, qualification_level, active,
    profession_id, qualification_id, brigade_id
  ) values (
    trim(p_id), trim(p_personnel_no), trim(p_name), v_profession.name,
    coalesce(v_qualification.level, 0), coalesce(p_active, true),
    v_profession.id, nullif(trim(p_qualification_id), ''),
    nullif(trim(p_brigade_id), '')
  )
  on conflict(id) do update set
    personnel_no = excluded.personnel_no,
    name = excluded.name,
    profession = excluded.profession,
    qualification_level = excluded.qualification_level,
    active = excluded.active,
    profession_id = excluded.profession_id,
    qualification_id = excluded.qualification_id,
    brigade_id = excluded.brigade_id
  returning * into r;

  delete from employee_qualifications where employee_id = r.id;
  if r.qualification_id is not null then
    insert into employee_qualifications(
      employee_id, qualification_id, valid_from, valid_to, is_primary, notes
    ) values (
      r.id, r.qualification_id, null, null, true, 'Синхронизировано из карточки персонала'
    );
  end if;

  insert into audit_log(
    actor_id, entity_type, entity_id, action, before_state, after_state
  ) values (
    auth.uid()::text, 'MES_EMPLOYEE', r.id, 'MASTER_DATA_SAVE', null, to_jsonb(r)
  );

  return to_jsonb(r);
end;
$$;

revoke all on function public.mes_master_save_employee(text,text,text,text,text,text,boolean) from public, anon;
grant execute on function public.mes_master_save_employee(text,text,text,text,text,text,boolean) to authenticated;

-- Central validation used both at assignment time and immediately before READY.
create or replace function public.mes_validate_task_qualification_and_equipment(
  p_task_id text
) returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_task production_tasks%rowtype;
  v_product_id text;
  v_operation_code text;
  v_required_qualification_id text;
  v_employee_id text;
  v_equipment_id text;
  v_has_equipment_scope boolean;
begin
  select * into v_task
  from production_tasks
  where id = p_task_id;
  if not found then
    raise exception 'Задание не найдено: %', p_task_id;
  end if;

  select o.product_id into v_product_id
  from production_orders o
  where o.id = v_task.order_id;
  if v_product_id is null then
    raise exception 'Продукт заказа задания не найден';
  end if;

  select r.code, r.required_qualification_id
    into v_operation_code, v_required_qualification_id
  from route_operations r
  where r.id = v_task.operation_id
    and r.product_id = v_product_id
    and r.active;
  if not found then
    raise exception 'Активная операция маршрута не найдена для задания';
  end if;

  if v_required_qualification_id is null then
    return;
  end if;

  select exists(
    select 1
    from qualification_equipment_access qea
    where qea.qualification_id = v_required_qualification_id
      and (qea.valid_from is null or qea.valid_from <= current_date)
      and (qea.valid_to is null or qea.valid_to >= current_date)
  ) into v_has_equipment_scope;

  for v_employee_id in
    select a.employee_id
    from task_assignments a
    where a.task_id = p_task_id
      and a.employee_id is not null
    order by a.employee_id
  loop
    if not exists(
      select 1
      from employee_qualifications eq
      join qualification_levels q
        on q.id = eq.qualification_id
       and q.active
      where eq.employee_id = v_employee_id
        and eq.qualification_id = v_required_qualification_id
        and (eq.valid_from is null or eq.valid_from <= current_date)
        and (eq.valid_to is null or eq.valid_to >= current_date)
    ) and not exists(
      select 1
      from employees e
      join qualification_levels q
        on q.id = e.qualification_id
       and q.active
      where e.id = v_employee_id
        and e.active
        and e.qualification_id = v_required_qualification_id
    ) then
      raise exception 'Сотрудник % не имеет требуемой квалификации % для операции %',
        v_employee_id, v_required_qualification_id, v_operation_code;
    end if;

    if v_has_equipment_scope then
      for v_equipment_id in
        select a.equipment_id
        from task_assignments a
        where a.task_id = p_task_id
          and a.equipment_id is not null
        order by a.equipment_id
      loop
        if not exists(
          select 1
          from qualification_equipment_access qea
          where qea.qualification_id = v_required_qualification_id
            and qea.equipment_id = v_equipment_id
            and (qea.valid_from is null or qea.valid_from <= current_date)
            and (qea.valid_to is null or qea.valid_to >= current_date)
        ) then
          raise exception 'Квалификация % сотрудника % не допускает оборудование %',
            v_required_qualification_id, v_employee_id, v_equipment_id;
        end if;
      end loop;
    end if;
  end loop;
end;
$$;

revoke all on function public.mes_validate_task_qualification_and_equipment(text) from public, anon;
grant execute on function public.mes_validate_task_qualification_and_equipment(text) to authenticated;

-- Existing task assignment guard, extended with exact qualification and
-- qualification-specific equipment access validation.
create or replace function public.mes_assign_task(
  p_task_id text,
  p_employee_ids jsonb default null,
  p_equipment_ids jsonb default null,
  p_expected_version integer default null
) returns production_tasks
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_task production_tasks%rowtype;
  v_plan_id text;
  v_employee_id text;
  v_equipment_id text;
  v_before jsonb;
  v_after jsonb;
  v_unique_employees text[];
  v_unique_equipment text[];
  v_product_id text;
  v_operation_work_center text;
  v_operation_work_center_id text;
  v_operation_code text;
  v_required_qualification integer;
  v_required_equipment_ids jsonb;
  v_effective_employee_ids jsonb;
  v_effective_equipment_ids jsonb;
begin
  if auth.uid() is null then raise exception 'MES authentication required'; end if;
  if not mes_has_role(array['ADMIN','PRODUCTION_MANAGER','PLANNER','DISPATCHER','MASTER']) then
    raise exception 'Недостаточно прав для назначения задания';
  end if;
  if p_employee_ids is not null and jsonb_typeof(p_employee_ids) <> 'array' then
    raise exception 'employeeIds должен быть массивом или null';
  end if;
  if p_equipment_ids is not null and jsonb_typeof(p_equipment_ids) <> 'array' then
    raise exception 'equipmentIds должен быть массивом или null';
  end if;
  if exists(select 1 from jsonb_array_elements(coalesce(p_employee_ids,'[]'::jsonb)) item where jsonb_typeof(item)<>'string')
     or exists(select 1 from jsonb_array_elements(coalesce(p_equipment_ids,'[]'::jsonb)) item where jsonb_typeof(item)<>'string') then
    raise exception 'employeeIds и equipmentIds должны содержать только строки';
  end if;

  select o.plan_id into v_plan_id
  from production_tasks t
  join production_orders o on o.id=t.order_id
  where t.id=p_task_id;
  if v_plan_id is null then raise exception 'Операционный план задания не найден: %',p_task_id; end if;
  perform 1 from operational_plans where id=v_plan_id for update;
  if not found then raise exception 'Операционный план не найден: %',v_plan_id; end if;

  select * into v_task from production_tasks where id=p_task_id for update;
  if not found then raise exception 'Задание не найдено: %',p_task_id; end if;
  if v_task.status in('COMPLETED','CANCELLED') then raise exception 'Нельзя менять назначения завершённого или отменённого задания'; end if;
  if p_expected_version is not null and v_task.version<>p_expected_version then
    raise exception 'Версия задания устарела: ожидается %, фактически %',p_expected_version,v_task.version;
  end if;

  select o.product_id into v_product_id from production_orders o where o.id=v_task.order_id;
  if v_product_id is null then raise exception 'Продукт заказа задания не найден'; end if;
  select r.work_center,r.work_center_id,r.code,r.required_qualification,r.required_equipment_ids
    into v_operation_work_center,v_operation_work_center_id,v_operation_code,v_required_qualification,v_required_equipment_ids
  from route_operations r
  where r.id=v_task.operation_id and r.product_id=v_product_id and r.active;
  if not found then raise exception 'Активная операция маршрута не найдена или не соответствует продукту заказа: %',v_task.operation_id; end if;

  select coalesce(jsonb_agg(a.employee_id order by a.employee_id) filter(where a.employee_id is not null),'[]'::jsonb),
         coalesce(jsonb_agg(a.equipment_id order by a.equipment_id) filter(where a.equipment_id is not null),'[]'::jsonb)
    into v_effective_employee_ids,v_effective_equipment_ids
  from task_assignments a where a.task_id=p_task_id;
  if p_employee_ids is not null then v_effective_employee_ids:=p_employee_ids; end if;
  if p_equipment_ids is not null then v_effective_equipment_ids:=p_equipment_ids; end if;

  select coalesce(array_agg(distinct value order by value),'{}'::text[]) into v_unique_employees
    from jsonb_array_elements_text(v_effective_employee_ids) as value where trim(value)<>'';
  select coalesce(array_agg(distinct value order by value),'{}'::text[]) into v_unique_equipment
    from jsonb_array_elements_text(v_effective_equipment_ids) as value where trim(value)<>'';

  foreach v_employee_id in array v_unique_employees loop
    perform pg_advisory_xact_lock(hashtextextended('mes:employee:'||v_employee_id,0));
  end loop;
  foreach v_equipment_id in array v_unique_equipment loop
    perform pg_advisory_xact_lock(hashtextextended('mes:equipment:'||v_equipment_id,0));
  end loop;

  if v_required_qualification is not null and cardinality(v_unique_employees)=0 then
    raise exception 'Для операции % требуется сотрудник с квалификацией не ниже %',v_operation_code,v_required_qualification;
  end if;

  foreach v_employee_id in array v_unique_employees loop
    if not exists(select 1 from employees where id=v_employee_id and active) then
      raise exception 'Активный сотрудник не найден: %',v_employee_id;
    end if;
    if v_required_qualification is not null and not exists(
      select 1 from employees where id=v_employee_id and active and qualification_level>=v_required_qualification
    ) then
      raise exception 'Сотрудник % не соответствует минимальной квалификации % для операции %',v_employee_id,v_required_qualification,v_operation_code;
    end if;
    if exists(
      select 1
      from task_assignments a
      join production_tasks other_task on other_task.id=a.task_id
      where a.employee_id=v_employee_id and other_task.id<>v_task.id
        and other_task.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED')
        and tstzrange(other_task.planned_start,other_task.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
    ) then
      raise exception 'Сотрудник % уже назначен на пересекающееся задание',v_employee_id;
    end if;
  end loop;

  foreach v_equipment_id in array v_unique_equipment loop
    if not exists(select 1 from equipment where id=v_equipment_id and active) then
      raise exception 'Активное оборудование не найдено: %',v_equipment_id;
    end if;
    if nullif(trim(v_operation_work_center_id),'') is not null then
      if not exists(select 1 from equipment e where e.id=v_equipment_id and e.active and e.work_center_id=trim(v_operation_work_center_id)) then
        raise exception 'Оборудование % относится к другому рабочему центру операции',v_equipment_id;
      end if;
    elsif not exists(select 1 from equipment e where e.id=v_equipment_id and e.active and e.work_center=trim(v_operation_work_center)) then
      raise exception 'Оборудование % относится к другому производственному участку операции',v_equipment_id;
    end if;
    if jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0
       and not exists(select 1 from jsonb_array_elements_text(v_required_equipment_ids) req where trim(req)=v_equipment_id) then
      raise exception 'Оборудование % не разрешено операцией %',v_equipment_id,v_operation_code;
    end if;
    if exists(
      select 1 from task_assignments a
      join production_tasks other_task on other_task.id=a.task_id
      where a.equipment_id=v_equipment_id and other_task.id<>v_task.id
        and other_task.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED')
        and tstzrange(other_task.planned_start,other_task.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
    ) then
      raise exception 'Оборудование % уже назначено на пересекающееся задание',v_equipment_id;
    end if;
    if exists(
      select 1 from equipment_blocks b
      where b.equipment_id=v_equipment_id
        and tstzrange(b.start_at,b.end_at,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
    ) then
      raise exception 'Оборудование % заблокировано на интервал задания',v_equipment_id;
    end if;
    if exists(
      select 1 from maintenance_orders m
      where m.equipment_id=v_equipment_id and m.status in('PLANNED','IN_PROGRESS')
        and tstzrange(m.planned_start,m.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
    ) then
      raise exception 'На оборудовании % запланировано обслуживание, пересекающееся с заданием',v_equipment_id;
    end if;
  end loop;

  if jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0
     and exists(
       select 1 from jsonb_array_elements_text(v_required_equipment_ids) req
       where not exists(select 1 from jsonb_array_elements_text(v_effective_equipment_ids) sel where trim(sel)=trim(req))
     ) then
    raise exception 'Не все обязательные единицы оборудования назначены для операции %',v_operation_code;
  end if;

  v_before:=jsonb_build_object(
    'status',v_task.status,'version',v_task.version,
    'employeeIds',coalesce((select jsonb_agg(a.employee_id order by a.employee_id) from task_assignments a where a.task_id=p_task_id and a.employee_id is not null),'[]'::jsonb),
    'equipmentIds',coalesce((select jsonb_agg(a.equipment_id order by a.equipment_id) from task_assignments a where a.task_id=p_task_id and a.equipment_id is not null),'[]'::jsonb)
  );

  delete from task_assignments where task_id=p_task_id;
  foreach v_employee_id in array v_unique_employees loop
    insert into task_assignments(task_id,employee_id) values(p_task_id,v_employee_id);
  end loop;
  foreach v_equipment_id in array v_unique_equipment loop
    insert into task_assignments(task_id,equipment_id) values(p_task_id,v_equipment_id);
  end loop;

  perform mes_validate_task_qualification_and_equipment(p_task_id);

  update production_tasks set
    status=case when status in('PLANNED','BLOCKED') and(cardinality(v_unique_employees)>0 or cardinality(v_unique_equipment)>0) then 'ASSIGNED' else status end,
    version=version+1
  where id=p_task_id returning * into v_task;

  v_after:=jsonb_build_object('status',v_task.status,'version',v_task.version,'employeeIds',to_jsonb(v_unique_employees),'equipmentIds',to_jsonb(v_unique_equipment));
  insert into audit_log(actor_id,entity_type,entity_id,action,before_state,after_state)
    values(v_actor,'PRODUCTION_TASK',p_task_id,'ASSIGNMENT_CHANGED',v_before,v_after);
  return v_task;
end;
$$;

revoke all on function public.mes_assign_task(text,jsonb,jsonb,integer) from public, anon;
grant execute on function public.mes_assign_task(text,jsonb,jsonb,integer) to authenticated;

-- READY is a second server-side gate, so a stale or externally-created
-- assignment cannot bypass the same exact qualification/equipment rules.
create or replace function public.mes_prepare_task(
  p_task_id text,
  p_expected_version integer default null
) returns production_tasks
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_task production_tasks%rowtype;
  v_product_id text;
  v_operation_work_center text;
  v_operation_work_center_id text;
  v_operation_code text;
  v_required_qualification integer;
  v_required_equipment_ids jsonb;
  v_employee_count integer;
  v_equipment_count integer;
  v_bad_employee text;
  v_bad_equipment text;
  v_missing_equipment text;
begin
  if auth.uid() is null then raise exception 'MES authentication required'; end if;
  if not mes_has_role(array['ADMIN','PRODUCTION_MANAGER','PLANNER','DISPATCHER','MASTER']) then
    raise exception 'Недостаточно прав для подготовки задания к выполнению';
  end if;

  select * into v_task from production_tasks where id=p_task_id for update;
  if not found then raise exception 'Задание не найдено: %',p_task_id; end if;
  if p_expected_version is not null and v_task.version<>p_expected_version then
    raise exception 'Версия задания устарела: ожидается %, фактически %',p_expected_version,v_task.version;
  end if;
  if v_task.status not in('ASSIGNED','BLOCKED') then
    raise exception 'Задание должно иметь статус ASSIGNED или BLOCKED, фактически %',v_task.status;
  end if;

  select o.product_id into v_product_id from production_orders o where o.id=v_task.order_id;
  if v_product_id is null then raise exception 'Продукт заказа задания не найден'; end if;
  select r.work_center,r.work_center_id,r.code,r.required_qualification,r.required_equipment_ids
    into v_operation_work_center,v_operation_work_center_id,v_operation_code,v_required_qualification,v_required_equipment_ids
  from route_operations r
  where r.id=v_task.operation_id and r.product_id=v_product_id and r.active;
  if not found then raise exception 'Активная операция маршрута не найдена для задания'; end if;

  select count(*) into v_employee_count from task_assignments where task_id=p_task_id and employee_id is not null;
  select count(*) into v_equipment_count from task_assignments where task_id=p_task_id and equipment_id is not null;
  if v_employee_count=0 then raise exception 'Нельзя перевести задание READY без назначенного сотрудника'; end if;
  if v_equipment_count=0 then raise exception 'Нельзя перевести задание READY без назначенного оборудования'; end if;

  select a.employee_id into v_bad_employee
  from task_assignments a
  left join employees e on e.id=a.employee_id
  where a.task_id=p_task_id and a.employee_id is not null
    and(e.id is null or not e.active or(v_required_qualification is not null and e.qualification_level<v_required_qualification))
  limit 1;
  if v_bad_employee is not null then
    raise exception 'Сотрудник % не соответствует требованиям операции %',v_bad_employee,v_operation_code;
  end if;

  select a.equipment_id into v_bad_equipment
  from task_assignments a
  left join equipment e on e.id=a.equipment_id
  where a.task_id=p_task_id and a.equipment_id is not null
    and(e.id is null or not e.active
      or(nullif(trim(v_operation_work_center_id),'') is not null and(e.work_center_id is null or e.work_center_id<>v_operation_work_center_id))
      or(nullif(trim(v_operation_work_center_id),'') is null and e.work_center<>v_operation_work_center))
  limit 1;
  if v_bad_equipment is not null then
    raise exception 'Оборудование % не соответствует рабочему центру операции %',v_bad_equipment,v_operation_code;
  end if;

  if jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0 then
    select a.equipment_id into v_bad_equipment
    from task_assignments a
    where a.task_id=p_task_id and a.equipment_id is not null
      and not exists(select 1 from jsonb_array_elements_text(v_required_equipment_ids) req where trim(req)=a.equipment_id)
    limit 1;
    if v_bad_equipment is not null then raise exception 'Оборудование % не разрешено операцией %',v_bad_equipment,v_operation_code; end if;

    select string_agg(required_id,',') into v_missing_equipment
    from jsonb_array_elements_text(coalesce(v_required_equipment_ids,'[]'::jsonb)) as required_id
    where not exists(select 1 from task_assignments a where a.task_id=p_task_id and a.equipment_id=required_id);
    if v_missing_equipment is not null then raise exception 'Не назначено обязательное оборудование: %',v_missing_equipment; end if;
  end if;

  perform mes_validate_task_qualification_and_equipment(p_task_id);

  if exists(
    select 1
    from task_assignments a
    join production_tasks other_task on other_task.id<>p_task_id
    join task_assignments other_assignment on other_assignment.task_id=other_task.id
      and((a.employee_id is not null and other_assignment.employee_id=a.employee_id)
        or(a.equipment_id is not null and other_assignment.equipment_id=a.equipment_id))
    where a.task_id=p_task_id
      and other_task.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED')
      and tstzrange(other_task.planned_start,other_task.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
  ) then
    raise exception 'Назначенные ресурсы пересекаются с другим активным заданием';
  end if;

  if exists(
    select 1 from task_assignments a
    join equipment_blocks b on b.equipment_id=a.equipment_id
    where a.task_id=p_task_id
      and tstzrange(b.start_at,b.end_at,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
  ) then
    raise exception 'Назначенное оборудование заблокировано в интервале задания';
  end if;

  if exists(
    select 1 from task_assignments a
    join maintenance_orders m on m.equipment_id=a.equipment_id
    where a.task_id=p_task_id and m.status in('PLANNED','IN_PROGRESS')
      and tstzrange(m.planned_start,m.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')
  ) then
    raise exception 'Назначенное оборудование занято обслуживанием в интервале задания';
  end if;

  update production_tasks set status='READY',version=version+1 where id=p_task_id returning * into v_task;
  insert into audit_log(actor_id,entity_type,entity_id,action,before_state,after_state)
    values(auth.uid()::text,'PRODUCTION_TASK',p_task_id,'TASK_PREPARED',jsonb_build_object('status','ASSIGNED','version',v_task.version-1),jsonb_build_object('status','READY','version',v_task.version));
  return v_task;
end;
$$;

revoke all on function public.mes_prepare_task(text,integer) from public, anon;
grant execute on function public.mes_prepare_task(text,integer) to authenticated;
