create or replace function public.mes_assert_route_operation_equipment_ids(
  p_work_center_id text,
  p_work_center text,
  p_required_equipment_ids jsonb
)
returns void language plpgsql security invoker set search_path=public as $$
declare v_item jsonb; v_equipment_id text; v_equipment_work_center_id text; v_equipment_work_center text;
begin
  if p_required_equipment_ids is null then return; end if;
  if jsonb_typeof(p_required_equipment_ids)<>'array' then raise exception 'required_equipment_ids должен быть JSON array'; end if;
  for v_item in select value from jsonb_array_elements(p_required_equipment_ids) loop
    if jsonb_typeof(v_item)<>'string' then raise exception 'required_equipment_ids должен содержать только строки'; end if;
    v_equipment_id:=trim(v_item#>>'{}'); if v_equipment_id='' then continue; end if;
    select e.work_center_id,e.work_center into v_equipment_work_center_id,v_equipment_work_center from equipment e where e.id=v_equipment_id and e.active;
    if not found then raise exception 'Активное оборудование не найдено: %',v_equipment_id; end if;
    if nullif(trim(p_work_center_id),'') is not null and nullif(trim(v_equipment_work_center_id),'') is not null then
      if trim(v_equipment_work_center_id)<>trim(p_work_center_id) then raise exception 'Оборудование % относится к другому рабочему центру',v_equipment_id; end if;
    elsif nullif(trim(p_work_center),'') is not null and trim(v_equipment_work_center)<>trim(p_work_center) then
      raise exception 'Оборудование % относится к другому производственному участку',v_equipment_id;
    end if;
  end loop;
end; $$;
revoke all on function public.mes_assert_route_operation_equipment_ids(text,text,jsonb) from public;

create or replace function public.mes_master_save_route_operation_v3(p_id text,p_route_id text,p_sequence integer,p_operation_id text,p_work_center_id text,p_required_qualification_id text,p_required_equipment_ids jsonb,p_setup_norm_hours numeric,p_labor_norm_hours_per_unit numeric,p_workers_required integer,p_active boolean default true)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r route_operations%rowtype; v_product_id text; v_work_center text; v_qualification_level integer; v_op operation_catalog%rowtype;
begin
  perform mes_require_master_editor(); select * into v_op from operation_catalog where id=trim(p_operation_id) and active=true; if not found then raise exception 'Выберите активную операцию из справочника'; end if;
  select product_id into v_product_id from routes where id=trim(p_route_id) and active=true; if v_product_id is null then raise exception 'Активный маршрут не найден: %',p_route_id; end if;
  select name into v_work_center from work_centers where id=trim(p_work_center_id) and active=true; if v_work_center is null then raise exception 'Активный рабочий центр не найден: %',p_work_center_id; end if;
  if p_required_qualification_id is not null then select level into v_qualification_level from qualification_levels where id=trim(p_required_qualification_id) and active=true; if v_qualification_level is null then raise exception 'Активная квалификация не найдена: %',p_required_qualification_id; end if; end if;
  p_required_equipment_ids:=coalesce(p_required_equipment_ids,'[]'::jsonb); perform mes_assert_route_operation_equipment_ids(p_work_center_id,v_work_center,p_required_equipment_ids);
  if p_sequence<=0 or p_workers_required<=0 or p_setup_norm_hours<0 or p_labor_norm_hours_per_unit<0 or(p_setup_norm_hours=0 and p_labor_norm_hours_per_unit=0) then raise exception 'Некорректная норма нормализованной операции'; end if;
  insert into route_operations(id,product_id,sequence,code,name,work_center,required_qualification,required_equipment_ids,setup_minutes,run_minutes_per_unit,active,labor_norm_hours_per_unit,setup_norm_hours,workers_required,route_id,work_center_id,required_qualification_id,operation_id)
  values(trim(p_id),v_product_id,p_sequence,v_op.code,v_op.name,v_work_center,v_qualification_level,p_required_equipment_ids,ceil(p_setup_norm_hours*60)::integer,round(p_labor_norm_hours_per_unit*60,6),coalesce(p_active,true),p_labor_norm_hours_per_unit,p_setup_norm_hours,p_workers_required,trim(p_route_id),trim(p_work_center_id),nullif(trim(p_required_qualification_id),''),v_op.id)
  on conflict(id) do update set product_id=excluded.product_id,sequence=excluded.sequence,code=excluded.code,name=excluded.name,work_center=excluded.work_center,required_qualification=excluded.required_qualification,required_equipment_ids=excluded.required_equipment_ids,setup_minutes=excluded.setup_minutes,run_minutes_per_unit=excluded.run_minutes_per_unit,active=excluded.active,labor_norm_hours_per_unit=excluded.labor_norm_hours_per_unit,setup_norm_hours=excluded.setup_norm_hours,workers_required=excluded.workers_required,route_id=excluded.route_id,work_center_id=excluded.work_center_id,required_qualification_id=excluded.required_qualification_id,operation_id=excluded.operation_id;
  select * into r from route_operations where id=trim(p_id); insert into audit_log(actor_id,entity_type,entity_id,action,after_state) values(auth.uid()::text,'MES_ROUTE_OPERATION',r.id,'MASTER_DATA_SAVE_V3',to_jsonb(r)); return to_jsonb(r);
end; $$;

create or replace function public.mes_master_save_route_operation_v2(p_id text,p_route_id text,p_sequence integer,p_code text,p_name text,p_work_center_id text,p_required_qualification_id text,p_required_equipment_ids jsonb,p_setup_norm_hours numeric,p_labor_norm_hours_per_unit numeric,p_workers_required integer,p_active boolean default true)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r route_operations%rowtype; v_product_id text; v_work_center text; v_qualification_level integer;
begin
  perform mes_require_master_editor(); if nullif(trim(p_id),'') is null or nullif(trim(p_route_id),'') is null or nullif(trim(p_code),'') is null or nullif(trim(p_name),'') is null or nullif(trim(p_work_center_id),'') is null then raise exception 'Обязательные поля нормализованной операции не заполнены'; end if;
  select product_id into v_product_id from routes where id=trim(p_route_id) and active=true; if v_product_id is null then raise exception 'Активный маршрут не найден: %',p_route_id; end if;
  select name into v_work_center from work_centers where id=trim(p_work_center_id) and active=true; if v_work_center is null then raise exception 'Активный рабочий центр не найден: %',p_work_center_id; end if;
  if p_required_qualification_id is not null then select level into v_qualification_level from qualification_levels where id=trim(p_required_qualification_id) and active=true; if v_qualification_level is null then raise exception 'Активная квалификация не найдена: %',p_required_qualification_id; end if; end if;
  p_required_equipment_ids:=coalesce(p_required_equipment_ids,'[]'::jsonb); perform mes_assert_route_operation_equipment_ids(p_work_center_id,v_work_center,p_required_equipment_ids);
  if p_sequence<=0 or p_workers_required<=0 or p_setup_norm_hours<0 or p_labor_norm_hours_per_unit<0 or(p_setup_norm_hours=0 and p_labor_norm_hours_per_unit=0) then raise exception 'Некорректная норма нормализованной операции'; end if;
  insert into route_operations(id,product_id,sequence,code,name,work_center,required_qualification,required_equipment_ids,setup_minutes,run_minutes_per_unit,active,labor_norm_hours_per_unit,setup_norm_hours,workers_required,route_id,work_center_id,required_qualification_id)
  values(trim(p_id),v_product_id,p_sequence,trim(p_code),trim(p_name),v_work_center,v_qualification_level,p_required_equipment_ids,ceil(p_setup_norm_hours*60)::integer,round(p_labor_norm_hours_per_unit*60,6),coalesce(p_active,true),p_labor_norm_hours_per_unit,p_setup_norm_hours,p_workers_required,trim(p_route_id),trim(p_work_center_id),nullif(trim(p_required_qualification_id),''))
  on conflict(id) do update set product_id=excluded.product_id,sequence=excluded.sequence,code=excluded.code,name=excluded.name,work_center=excluded.work_center,required_qualification=excluded.required_qualification,required_equipment_ids=excluded.required_equipment_ids,setup_minutes=excluded.setup_minutes,run_minutes_per_unit=excluded.run_minutes_per_unit,active=excluded.active,labor_norm_hours_per_unit=excluded.labor_norm_hours_per_unit,setup_norm_hours=excluded.setup_norm_hours,workers_required=excluded.workers_required,route_id=excluded.route_id,work_center_id=excluded.work_center_id,required_qualification_id=excluded.required_qualification_id;
  select * into r from route_operations where id=trim(p_id); insert into audit_log(actor_id,entity_type,entity_id,action,after_state) values(auth.uid()::text,'MES_ROUTE_OPERATION',r.id,'MASTER_DATA_SAVE_V2',to_jsonb(r)); return to_jsonb(r);
end; $$;

create or replace function public.mes_master_save_route_operation(p_id text,p_product_id text,p_sequence integer,p_code text,p_name text,p_work_center text,p_required_qualification integer,p_required_equipment_ids jsonb,p_setup_norm_hours numeric,p_labor_norm_hours_per_unit numeric,p_workers_required integer,p_active boolean)
returns route_operations language plpgsql security definer set search_path=public as $$
declare v route_operations%rowtype;
begin
  perform mes_require_master_editor(); if nullif(trim(p_id),'') is null or nullif(trim(p_product_id),'') is null or nullif(trim(p_code),'') is null or nullif(trim(p_name),'') is null or nullif(trim(p_work_center),'') is null then raise exception 'Для операции обязательны id, product_id, code, name и work_center'; end if;
  if not exists(select 1 from products where id=trim(p_product_id)) then raise exception 'Продукт % не существует',p_product_id; end if;
  p_required_equipment_ids:=coalesce(p_required_equipment_ids,'[]'::jsonb); perform mes_assert_route_operation_equipment_ids(null,p_work_center,p_required_equipment_ids);
  if p_sequence<=0 or coalesce(p_required_qualification,0)<0 or coalesce(p_workers_required,1)<=0 or coalesce(p_setup_norm_hours,0)<0 or coalesce(p_labor_norm_hours_per_unit,0)<0 or(coalesce(p_setup_norm_hours,0)=0 and coalesce(p_labor_norm_hours_per_unit,0)=0) then raise exception 'Некорректная норма или параметры route operation'; end if;
  insert into route_operations(id,product_id,sequence,code,name,work_center,required_qualification,required_equipment_ids,setup_minutes,run_minutes_per_unit,active,labor_norm_hours_per_unit,setup_norm_hours,workers_required)
  values(trim(p_id),trim(p_product_id),p_sequence,trim(p_code),trim(p_name),trim(p_work_center),coalesce(p_required_qualification,0),p_required_equipment_ids,ceil(coalesce(p_setup_norm_hours,0)*60)::integer,round(coalesce(p_labor_norm_hours_per_unit,0)*60,6),coalesce(p_active,true),coalesce(p_labor_norm_hours_per_unit,0),coalesce(p_setup_norm_hours,0),coalesce(p_workers_required,1))
  on conflict(id) do update set product_id=excluded.product_id,sequence=excluded.sequence,code=excluded.code,name=excluded.name,work_center=excluded.work_center,required_qualification=excluded.required_qualification,required_equipment_ids=excluded.required_equipment_ids,setup_minutes=excluded.setup_minutes,run_minutes_per_unit=excluded.run_minutes_per_unit,active=excluded.active,labor_norm_hours_per_unit=excluded.labor_norm_hours_per_unit,setup_norm_hours=excluded.setup_norm_hours,workers_required=excluded.workers_required returning * into v;
  insert into audit_log(actor_id,entity_type,entity_id,action,after_state) values(auth.uid()::text,'MES_ROUTE_OPERATION',v.id,'MASTER_DATA_SAVE',to_jsonb(v)); return v;
end; $$;

create or replace function public.mes_assign_task(p_task_id text,p_employee_ids jsonb default null::jsonb,p_equipment_ids jsonb default null::jsonb,p_expected_version integer default null::integer)
returns production_tasks language plpgsql security definer set search_path=public as $$
declare v_task production_tasks%rowtype; v_actor text:=auth.uid()::text; v_plan_id text; v_employee_id text; v_equipment_id text; v_before jsonb; v_after jsonb; v_unique_employees text[]; v_unique_equipment text[]; v_product_id text; v_operation_work_center text; v_operation_work_center_id text; v_operation_code text; v_required_qualification integer; v_required_equipment_ids jsonb; v_effective_employee_ids jsonb; v_effective_equipment_ids jsonb;
begin
 if auth.uid() is null then raise exception 'MES authentication required'; end if; if not mes_has_role(array['ADMIN','PRODUCTION_MANAGER','PLANNER','DISPATCHER','MASTER']) then raise exception 'Недостаточно прав для назначения задания'; end if;
 if p_employee_ids is not null and jsonb_typeof(p_employee_ids)<>'array' then raise exception 'employeeIds должен быть массивом или null'; end if; if p_equipment_ids is not null and jsonb_typeof(p_equipment_ids)<>'array' then raise exception 'equipmentIds должен быть массивом или null'; end if;
 if exists(select 1 from jsonb_array_elements(coalesce(p_employee_ids,'[]'::jsonb)) item where jsonb_typeof(item)<>'string') or exists(select 1 from jsonb_array_elements(coalesce(p_equipment_ids,'[]'::jsonb)) item where jsonb_typeof(item)<>'string') then raise exception 'employeeIds и equipmentIds должны содержать только строки'; end if;
 select o.plan_id into v_plan_id from production_tasks t join production_orders o on o.id=t.order_id where t.id=p_task_id; if v_plan_id is null then raise exception 'Операционный план задания не найден: %',p_task_id; end if; perform 1 from operational_plans where id=v_plan_id for update; if not found then raise exception 'Операционный план не найден: %',v_plan_id; end if;
 select * into v_task from production_tasks where id=p_task_id for update; if not found then raise exception 'Задание не найдено: %',p_task_id; end if; if v_task.status in('COMPLETED','CANCELLED') then raise exception 'Нельзя менять назначения завершённого или отменённого задания'; end if; if p_expected_version is not null and v_task.version<>p_expected_version then raise exception 'Версия задания устарела: ожидается %, фактически %',p_expected_version,v_task.version; end if;
 select o.product_id into v_product_id from production_orders o where o.id=v_task.order_id; if v_product_id is null then raise exception 'Продукт заказа задания не найден'; end if;
 select r.work_center,r.work_center_id,r.code,r.required_qualification,r.required_equipment_ids into v_operation_work_center,v_operation_work_center_id,v_operation_code,v_required_qualification,v_required_equipment_ids from route_operations r where r.id=v_task.operation_id and r.product_id=v_product_id and r.active; if not found then raise exception 'Активная операция маршрута не найдена или не соответствует продукту заказа: %',v_task.operation_id; end if;
 select coalesce(jsonb_agg(a.employee_id order by a.employee_id) filter(where a.employee_id is not null),'[]'::jsonb),coalesce(jsonb_agg(a.equipment_id order by a.equipment_id) filter(where a.equipment_id is not null),'[]'::jsonb) into v_effective_employee_ids,v_effective_equipment_ids from task_assignments a where a.task_id=p_task_id; if p_employee_ids is not null then v_effective_employee_ids:=p_employee_ids; end if; if p_equipment_ids is not null then v_effective_equipment_ids:=p_equipment_ids; end if;
 select coalesce(array_agg(distinct value order by value),'{}'::text[]) into v_unique_employees from jsonb_array_elements_text(v_effective_employee_ids) as value where trim(value)<>''; select coalesce(array_agg(distinct value order by value),'{}'::text[]) into v_unique_equipment from jsonb_array_elements_text(v_effective_equipment_ids) as value where trim(value)<>'';
 foreach v_employee_id in array v_unique_employees loop perform pg_advisory_xact_lock(hashtextextended('mes:employee:'||v_employee_id,0)); end loop; foreach v_equipment_id in array v_unique_equipment loop perform pg_advisory_xact_lock(hashtextextended('mes:equipment:'||v_equipment_id,0)); end loop;
 if v_required_qualification is not null and cardinality(v_unique_employees)=0 then raise exception 'Для операции % требуется сотрудник с квалификацией не ниже %',v_operation_code,v_required_qualification; end if;
 foreach v_employee_id in array v_unique_employees loop
  if not exists(select 1 from employees where id=v_employee_id and active) then raise exception 'Активный сотрудник не найден: %',v_employee_id; end if; if v_required_qualification is not null and not exists(select 1 from employees where id=v_employee_id and active and qualification_level>=v_required_qualification) then raise exception 'Сотрудник % не соответствует минимальной квалификации % для операции %',v_employee_id,v_required_qualification,v_operation_code; end if;
  if exists(select 1 from task_assignments a join production_tasks other_task on other_task.id=a.task_id where a.employee_id=v_employee_id and other_task.id<>v_task.id and other_task.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED') and tstzrange(other_task.planned_start,other_task.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'Сотрудник % уже назначен на пересекающееся задание',v_employee_id; end if;
 end loop;
 foreach v_equipment_id in array v_unique_equipment loop
  if not exists(select 1 from equipment where id=v_equipment_id and active) then raise exception 'Активное оборудование не найдено: %',v_equipment_id; end if;
  if nullif(trim(v_operation_work_center_id),'') is not null then if not exists(select 1 from equipment e where e.id=v_equipment_id and e.active and e.work_center_id=trim(v_operation_work_center_id)) then raise exception 'Оборудование % относится к другому рабочему центру операции',v_equipment_id; end if; elsif not exists(select 1 from equipment e where e.id=v_equipment_id and e.active and e.work_center=trim(v_operation_work_center)) then raise exception 'Оборудование % относится к другому производственному участку операции',v_equipment_id; end if;
  if jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0 and not exists(select 1 from jsonb_array_elements_text(v_required_equipment_ids) req where trim(req)=v_equipment_id) then raise exception 'Оборудование % не разрешено операцией %',v_equipment_id,v_operation_code; end if;
  if exists(select 1 from task_assignments a join production_tasks other_task on other_task.id=a.task_id where a.equipment_id=v_equipment_id and other_task.id<>v_task.id and other_task.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED') and tstzrange(other_task.planned_start,other_task.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'Оборудование % уже назначено на пересекающееся задание',v_equipment_id; end if;
  if exists(select 1 from equipment_blocks b where b.equipment_id=v_equipment_id and tstzrange(b.start_at,b.end_at,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'Оборудование % заблокировано на интервал задания',v_equipment_id; end if;
  if exists(select 1 from maintenance_orders m where m.equipment_id=v_equipment_id and m.status in('PLANNED','IN_PROGRESS') and tstzrange(m.planned_start,m.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'На оборудовании % запланировано обслуживание, пересекающееся с заданием',v_equipment_id; end if;
 end loop;
 if jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0 and exists(select 1 from jsonb_array_elements_text(v_required_equipment_ids) req where not exists(select 1 from jsonb_array_elements_text(v_effective_equipment_ids) sel where trim(sel)=trim(req))) then raise exception 'Не все обязательные единицы оборудования назначены для операции %',v_operation_code; end if;
 v_before:=jsonb_build_object('status',v_task.status,'version',v_task.version,'employeeIds',coalesce((select jsonb_agg(a.employee_id order by a.employee_id) from task_assignments a where a.task_id=p_task_id and a.employee_id is not null),'[]'::jsonb),'equipmentIds',coalesce((select jsonb_agg(a.equipment_id order by a.equipment_id) from task_assignments a where a.task_id=p_task_id and a.equipment_id is not null),'[]'::jsonb)); delete from task_assignments where task_id=p_task_id;
 foreach v_employee_id in array v_unique_employees loop insert into task_assignments(task_id,employee_id) values(p_task_id,v_employee_id); end loop; foreach v_equipment_id in array v_unique_equipment loop insert into task_assignments(task_id,equipment_id) values(p_task_id,v_equipment_id); end loop;
 update production_tasks set status=case when status in('PLANNED','BLOCKED') and(cardinality(v_unique_employees)>0 or cardinality(v_unique_equipment)>0) then 'ASSIGNED' else status end,version=version+1 where id=p_task_id returning * into v_task;
 v_after:=jsonb_build_object('status',v_task.status,'version',v_task.version,'employeeIds',to_jsonb(v_unique_employees),'equipmentIds',to_jsonb(v_unique_equipment)); insert into audit_log(actor_id,entity_type,entity_id,action,before_state,after_state) values(v_actor,'PRODUCTION_TASK',p_task_id,'ASSIGNMENT_CHANGED',v_before,v_after); return v_task;
end; $$;

create or replace function public.mes_prepare_task(p_task_id text,p_expected_version integer default null::integer)
returns production_tasks language plpgsql security definer set search_path=public as $$
declare v_task production_tasks%rowtype; v_product_id text; v_operation_work_center text; v_operation_work_center_id text; v_operation_code text; v_required_qualification integer; v_required_equipment_ids jsonb; v_employee_count integer; v_equipment_count integer; v_bad_employee text; v_bad_equipment text; v_missing_equipment text;
begin
 if auth.uid() is null then raise exception 'MES authentication required'; end if; if not mes_has_role(array['ADMIN','PRODUCTION_MANAGER','PLANNER','DISPATCHER','MASTER']) then raise exception 'Недостаточно прав для подготовки задания к выполнению'; end if;
 select * into v_task from production_tasks where id=p_task_id for update; if not found then raise exception 'Задание не найдено: %',p_task_id; end if; if p_expected_version is not null and v_task.version<>p_expected_version then raise exception 'Версия задания устарела: ожидается %, фактически %',p_expected_version,v_task.version; end if; if v_task.status not in('ASSIGNED','BLOCKED') then raise exception 'Задание должно иметь статус ASSIGNED или BLOCKED, фактически %',v_task.status; end if;
 select o.product_id into v_product_id from production_orders o where o.id=v_task.order_id; if v_product_id is null then raise exception 'Продукт заказа задания не найден'; end if;
 select r.work_center,r.work_center_id,r.code,r.required_qualification,r.required_equipment_ids into v_operation_work_center,v_operation_work_center_id,v_operation_code,v_required_qualification,v_required_equipment_ids from route_operations r where r.id=v_task.operation_id and r.product_id=v_product_id and r.active; if not found then raise exception 'Активная операция маршрута не найдена для задания'; end if;
 select count(*) into v_employee_count from task_assignments where task_id=p_task_id and employee_id is not null; select count(*) into v_equipment_count from task_assignments where task_id=p_task_id and equipment_id is not null; if v_employee_count=0 then raise exception 'Нельзя перевести задание READY без назначенного сотрудника'; end if; if v_equipment_count=0 then raise exception 'Нельзя перевести задание READY без назначенного оборудования'; end if;
 select a.employee_id into v_bad_employee from task_assignments a left join employees e on e.id=a.employee_id where a.task_id=p_task_id and a.employee_id is not null and(e.id is null or not e.active or(v_required_qualification is not null and e.qualification_level<v_required_qualification)) limit 1; if v_bad_employee is not null then raise exception 'Сотрудник % не соответствует требованиям операции %',v_bad_employee,v_operation_code; end if;
 select a.equipment_id into v_bad_equipment from task_assignments a left join equipment e on e.id=a.equipment_id where a.task_id=p_task_id and a.equipment_id is not null and(e.id is null or not e.active or(nullif(trim(v_operation_work_center_id),'') is not null and(e.work_center_id is null or e.work_center_id<>v_operation_work_center_id)) or(nullif(trim(v_operation_work_center_id),'') is null and e.work_center<>v_operation_work_center)) limit 1; if v_bad_equipment is not null then raise exception 'Оборудование % не соответствует рабочему центру операции %',v_bad_equipment,v_operation_code; end if;
 if jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0 then select a.equipment_id into v_bad_equipment from task_assignments a where a.task_id=p_task_id and a.equipment_id is not null and not exists(select 1 from jsonb_array_elements_text(v_required_equipment_ids) req where trim(req)=a.equipment_id) limit 1; if v_bad_equipment is not null then raise exception 'Оборудование % не разрешено операцией %',v_bad_equipment,v_operation_code; end if; end if;
 select string_agg(required_id,',') into v_missing_equipment from jsonb_array_elements_text(coalesce(v_required_equipment_ids,'[]'::jsonb)) as required_id where not exists(select 1 from task_assignments a where a.task_id=p_task_id and a.equipment_id=required_id); if v_missing_equipment is not null then raise exception 'Не назначено обязательное оборудование: %',v_missing_equipment; end if;
 if exists(select 1 from task_assignments a join production_tasks other_task on other_task.id<>p_task_id join task_assignments other_assignment on other_assignment.task_id=other_task.id and((a.employee_id is not null and other_assignment.employee_id=a.employee_id) or(a.equipment_id is not null and other_assignment.equipment_id=a.equipment_id)) where a.task_id=p_task_id and other_task.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED') and tstzrange(other_task.planned_start,other_task.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'Назначенные ресурсы пересекаются с другим активным заданием'; end if;
 if exists(select 1 from task_assignments a join equipment_blocks b on b.equipment_id=a.equipment_id where a.task_id=p_task_id and tstzrange(b.start_at,b.end_at,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'Назначенное оборудование заблокировано в интервале задания'; end if;
 if exists(select 1 from task_assignments a join maintenance_orders m on m.equipment_id=a.equipment_id where a.task_id=p_task_id and m.status in('PLANNED','IN_PROGRESS') and tstzrange(m.planned_start,m.planned_end,'[)')&&tstzrange(v_task.planned_start,v_task.planned_end,'[)')) then raise exception 'Назначенное оборудование занято обслуживанием в интервале задания'; end if;
 update production_tasks set status='READY',version=version+1 where id=p_task_id returning * into v_task; insert into audit_log(actor_id,entity_type,entity_id,action,before_state,after_state) values(auth.uid()::text,'PRODUCTION_TASK',p_task_id,'TASK_PREPARED',jsonb_build_object('status','ASSIGNED','version',v_task.version-1),jsonb_build_object('status','READY','version',v_task.version)); return v_task;
end; $$;

create or replace function public.mes_recommend_task_resources(p_task_id text)
returns table(resource_type text,resource_id text,resource_name text,score numeric,reasons jsonb) language plpgsql security definer set search_path=public as $$
declare v_task production_tasks%rowtype; v_product_id text; v_work_center text; v_work_center_id text; v_operation_code text; v_required_qualification integer; v_required_equipment_ids jsonb; v_work_range tstzrange;
begin
 if auth.uid() is null then raise exception 'MES authentication required'; end if; if not mes_has_role(array['ADMIN','PRODUCTION_MANAGER','PLANNER','DISPATCHER','MASTER']) then raise exception 'Недостаточно прав для подбора ресурсов'; end if;
 select * into v_task from production_tasks where id=p_task_id; if not found then raise exception 'Задание не найдено: %',p_task_id; end if; if v_task.status in('COMPLETED','CANCELLED') then raise exception 'Для завершённого или отменённого задания подбор ресурсов недоступен'; end if;
 select o.product_id into v_product_id from production_orders o where o.id=v_task.order_id; select r.work_center,r.work_center_id,r.code,r.required_qualification,r.required_equipment_ids into v_work_center,v_work_center_id,v_operation_code,v_required_qualification,v_required_equipment_ids from route_operations r where r.id=v_task.operation_id and r.product_id=v_product_id and r.active; if not found then raise exception 'Активная операция маршрута не найдена'; end if; v_work_range:=tstzrange(v_task.planned_start,v_task.planned_end,'[)');
 return query with employee_candidates as(select e.id,e.name,(greatest(0,e.qualification_level-coalesce(v_required_qualification,0))*10+(select count(*) from task_assignments a join production_tasks t on t.id=a.task_id where a.employee_id=e.id and t.id<>v_task.id and t.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED')))::numeric candidate_score,jsonb_build_array(format('Квалификация: %s',e.qualification_level),'Сотрудник активен','Нет пересечения по заданиям','Календарь/смена покрывают весь интервал') candidate_reasons from employees e join lateral(select range_agg(tstzrange(((cd.date::text||' 00:00:00+00')::timestamptz)+(s.start_minute*interval '1 minute'),((cd.date::text||' 00:00:00+00')::timestamptz)+((s.start_minute+s.duration_minutes)*interval '1 minute'),'[)')) work_range from calendar_days cd join employee_schedules es on es.employee_id=e.id and es.date=cd.date and es.status='WORK' join shift_definitions s on s.active and s.id in(select jsonb_array_elements_text(coalesce(cd.shift_ids,'[]'::jsonb))) and s.id in(select jsonb_array_elements_text(coalesce(es.shift_ids,'[]'::jsonb))) where cd.is_working and cd.date between(v_task.planned_start at time zone 'UTC')::date and((v_task.planned_end-interval '1 microsecond') at time zone 'UTC')::date) availability on availability.work_range @> v_work_range where e.active and(v_required_qualification is null or e.qualification_level>=v_required_qualification) and not exists(select 1 from task_assignments a join production_tasks t on t.id=a.task_id where a.employee_id=e.id and t.id<>v_task.id and t.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED') and tstzrange(t.planned_start,t.planned_end,'[)')&&v_work_range)) select 'EMPLOYEE',ec.id,ec.name,ec.candidate_score,ec.candidate_reasons from employee_candidates ec order by ec.candidate_score,ec.name limit 20;
 return query with equipment_candidates as(select e.id,e.name,(select count(*) from task_assignments a join production_tasks t on t.id=a.task_id where a.equipment_id=e.id and t.id<>v_task.id and t.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED') and tstzrange(t.planned_start,t.planned_end,'[)')&&v_work_range)::numeric candidate_score,jsonb_build_array(format('Рабочий центр: %s',coalesce(e.work_center_id,e.work_center)),case when jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))>0 then 'Разрешено операцией маршрута' else 'Допустимо оборудованием рабочего центра' end,'Оборудование активно','Нет пересечения по заданиям','Нет блока или обслуживания на интервале') candidate_reasons from equipment e where e.active and((nullif(trim(v_work_center_id),'') is not null and e.work_center_id=v_work_center_id) or(nullif(trim(v_work_center_id),'') is null and e.work_center=v_work_center)) and(jsonb_array_length(coalesce(v_required_equipment_ids,'[]'::jsonb))=0 or e.id in(select jsonb_array_elements_text(v_required_equipment_ids))) and not exists(select 1 from task_assignments a join production_tasks t on t.id=a.task_id where a.equipment_id=e.id and t.id<>v_task.id and t.status in('ASSIGNED','READY','RUNNING','PAUSED','PARTIALLY_COMPLETED') and tstzrange(t.planned_start,t.planned_end,'[)')&&v_work_range) and not exists(select 1 from equipment_blocks b where b.equipment_id=e.id and tstzrange(b.start_at,b.end_at,'[)')&&v_work_range) and not exists(select 1 from maintenance_orders m where m.equipment_id=e.id and m.status in('PLANNED','IN_PROGRESS') and tstzrange(m.planned_start,m.planned_end,'[)')&&v_work_range)) select 'EQUIPMENT',ec.id,ec.name,ec.candidate_score,ec.candidate_reasons from equipment_candidates ec order by ec.candidate_score,ec.name limit 20;
end; $$;

drop index if exists public.uq_equipment_capability;
