import { DowntimeEvent, ProductionOrder, ProductionResult, ProductionTask } from '../types';
export interface TaskPlanFact { taskId:string; plannedQuantity:number; goodQuantity:number; scrapQuantity:number; completionPercent:number; quantityVariance:number; status:ProductionTask['status']; plannedStart:string; plannedEnd:string; actualStart?:string; actualEnd?:string; scheduleVarianceMinutes?:number; overdue:boolean }
export interface OrderPlanFact { orderId:string; orderNumber:string; plannedQuantity:number; goodQuantity:number; scrapQuantity:number; completionPercent:number; quantityVariance:number; overdue:boolean; dueAt:string }
export interface PlanFactSummary { plannedQuantity:number; goodQuantity:number; scrapQuantity:number; quantityVariance:number; completionPercent:number; scrapPercent:number; completedTasks:number; activeTasks:number; overdueTasks:number; downtimeMinutes:number; downtimeEvents:number }
export interface ReplanItem { taskId:string; reason:'DOWNTIME'|'CASCADE'; equipmentId:string; oldStart:string; oldEnd:string; newStart:string; newEnd:string; deltaMinutes:number }
export interface ReplanConflict { taskId:string; reason:'HORIZON'; message:string }
export interface ReplanPreview { affected:ReplanItem[]; conflicts:ReplanConflict[] }
const percent=(v:number,b:number)=>b<=0?0:Math.round((v/b)*1000)/10;
const minutesBetween=(s?:string,e?:string)=>!s||!e?undefined:Math.round((new Date(e).getTime()-new Date(s).getTime())/60000);
function taskResultTotals(taskId:string,results:ProductionResult[]){return results.reduce((t,r)=>r.taskId===taskId?{good:t.good+r.goodQuantity,scrap:t.scrap+r.scrapQuantity}:t,{good:0,scrap:0});}
export function buildTaskPlanFact(tasks:ProductionTask[],results:ProductionResult[],now=new Date()):TaskPlanFact[]{return tasks.map(task=>{const totals=taskResultTotals(task.id,results);const referenceEnd=task.actualEnd?new Date(task.actualEnd):now;const overdue=referenceEnd.getTime()>new Date(task.plannedEnd).getTime()&&task.actualQuantity<task.plannedQuantity;return{taskId:task.id,plannedQuantity:task.plannedQuantity,goodQuantity:totals.good,scrapQuantity:totals.scrap,completionPercent:percent(totals.good,task.plannedQuantity),quantityVariance:totals.good-task.plannedQuantity,status:task.status,plannedStart:task.plannedStart,plannedEnd:task.plannedEnd,actualStart:task.actualStart,actualEnd:task.actualEnd,scheduleVarianceMinutes:task.actualEnd?minutesBetween(task.plannedEnd,task.actualEnd):(overdue?minutesBetween(task.plannedEnd,now.toISOString()):undefined),overdue};});}
export function buildOrderPlanFact(orders:ProductionOrder[],tasks:ProductionTask[],results:ProductionResult[],now=new Date()):OrderPlanFact[]{return orders.map(order=>{const orderTasks=tasks.filter(task=>task.orderId===order.id);const good=orderTasks.reduce((s,t)=>s+taskResultTotals(t.id,results).good,0);const scrap=orderTasks.reduce((s,t)=>s+taskResultTotals(t.id,results).scrap,0);return{orderId:order.id,orderNumber:order.number,plannedQuantity:order.quantity,goodQuantity:good,scrapQuantity:scrap,completionPercent:percent(good,order.quantity),quantityVariance:good-order.quantity,overdue:good<order.quantity&&now.getTime()>new Date(order.dueAt).getTime(),dueAt:order.dueAt};});}
export function calculateDowntimeMinutes(downtimes:DowntimeEvent[],now=new Date()):number{return downtimes.reduce((sum,e)=>sum+Math.max(0,Math.round(((e.endedAt?new Date(e.endedAt):now).getTime()-new Date(e.startedAt).getTime())/60000)),0);}
export function buildPlanFactSummary(tasks:ProductionTask[],results:ProductionResult[],downtimes:DowntimeEvent[],now=new Date()):PlanFactSummary{const good=results.reduce((s,r)=>s+r.goodQuantity,0),scrap=results.reduce((s,r)=>s+r.scrapQuantity,0),planned=tasks.reduce((s,t)=>s+t.plannedQuantity,0);return{plannedQuantity:planned,goodQuantity:good,scrapQuantity:scrap,quantityVariance:good-planned,completionPercent:percent(good,planned),scrapPercent:percent(scrap,good+scrap),completedTasks:tasks.filter(t=>t.status==='COMPLETED').length,activeTasks:tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length,overdueTasks:buildTaskPlanFact(tasks,results,now).filter(x=>x.overdue).length,downtimeMinutes:calculateDowntimeMinutes(downtimes,now),downtimeEvents:downtimes.length};}
function replanDuration(t:ProductionTask){return Math.max(60000,new Date(t.plannedEnd).getTime()-new Date(t.plannedStart).getTime());}
function overlap(s:number,e:number,t:ProductionTask){return s<new Date(t.plannedEnd).getTime()&&new Date(t.plannedStart).getTime()<e;}
export function previewDowntimeReplan(tasks:ProductionTask[],downtimes:DowntimeEvent[],horizonEnd:string):ReplanPreview{const horizon=new Date(horizonEnd).getTime(),affected:ReplanItem[]=[],conflicts:ReplanConflict[]=[],work=tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).map(t=>({...t}));for(const d of downtimes){const s=new Date(d.startedAt).getTime(),e=d.endedAt?new Date(d.endedAt).getTime():horizon;if(!(e>s))continue;for(const t of work.filter(x=>x.assignedEquipmentIds.includes(d.equipmentId)).sort((a,b)=>new Date(a.plannedStart).getTime()-new Date(b.plannedStart).getTime())){const os=new Date(t.plannedStart).getTime();if(!overlap(s,e,t))continue;const ns=Math.max(os,e),ne=ns+replanDuration(t);if(ne>horizon){conflicts.push({taskId:t.id,reason:'HORIZON',message:`Задание ${t.id} не помещается в горизонт после простоя.`});continue}affected.push({taskId:t.id,reason:affected.some(x=>x.taskId===t.id)?'CASCADE':'DOWNTIME',equipmentId:d.equipmentId,oldStart:new Date(os).toISOString(),oldEnd:t.plannedEnd,newStart:new Date(ns).toISOString(),newEnd:new Date(ne).toISOString(),deltaMinutes:Math.round((ns-os)/60000)});t.plannedStart=new Date(ns).toISOString();t.plannedEnd=new Date(ne).toISOString();}}return{affected,conflicts};}
export function applyReplan(tasks:ProductionTask[],preview:ReplanPreview):void{for(const i of preview.affected){const t=tasks.find(x=>x.id===i.taskId);if(!t||['COMPLETED','CANCELLED'].includes(t.status))continue;t.plannedStart=i.newStart;t.plannedEnd=i.newEnd;t.version+=1;}}
