import { getMesAuthState } from './integration/auth';
import { mountMesRegistration } from './integration/mesRegistration';
import { mountQualityPage } from './ui/qualityPage';
import { mountMesDashboardPage } from './ui/mesDashboardPage';
import { mountOrdersPage } from './ui/ordersPage';
import { mountEventJournalPage } from './ui/eventJournalPage';
import { mountIntegrityPage } from './ui/integrityPage';
import { mountOperationalWorkflowPage } from './ui/operationalWorkflowPage';
import { mountWorkflowMonitorPage } from './ui/workflowMonitorPage';
import { mountProductionEntryPage } from './ui/productionEntryPage';
import { mountOperatorDowntimePage } from './ui/operatorDowntimePage';
import { mountEquipmentOperationsPage } from './ui/equipmentOperationsPage';
import { mountDispatchGanttPage } from './ui/dispatchGanttPage';
import { mountImportCenterPage } from './ui/importCenterPage';
import { mountMesUserAdminPage } from './ui/mesUserAdminPage';
import { mountMesWorkspaceNav } from './ui/mesWorkspaceNav';
import { mountNsiAdminPage } from './ui/nsiAdminPage';
import { mountProductionRequestsPage } from './ui/productionRequestsPage';
import { getMesSupabaseClient } from './services/supabase';
const supabase = getMesSupabaseClient();
function reportRemoteFailure(error: unknown): void { window.alert(error instanceof Error ? error.message : 'Серверная операция MES не выполнена'); window.location.reload(); }
void import('./main').then(async () => {
 if (!supabase) return;
 mountMesRegistration(supabase);
 const auth = await getMesAuthState(supabase, { hydrateSnapshot: false }); if (!auth.identity) return;
 const app = document.querySelector<HTMLDivElement>('#app') ?? document.body;
 await mountMesDashboardPage(app, supabase);
 const workspace = document.createElement('div');
 workspace.id = 'mes-persistent-workspaces';
 workspace.style.maxWidth = '1440px';
 workspace.style.margin = '0 auto';
 workspace.style.padding = '0 16px 48px';
 document.body.appendChild(workspace);
 await mountOperationalWorkflowPage(workspace, supabase);
 await mountProductionEntryPage(workspace, supabase);
 await mountOperatorDowntimePage(workspace, supabase);
 await mountEquipmentOperationsPage(workspace, supabase);
 await mountDispatchGanttPage(workspace, supabase);
 await mountOrdersPage(workspace, supabase);
 await mountProductionRequestsPage(workspace, supabase);
 await mountQualityPage(workspace, supabase);
 await mountEventJournalPage(workspace, supabase);
 await mountIntegrityPage(workspace, supabase);
 await mountWorkflowMonitorPage(workspace, supabase);
 await mountNsiAdminPage(workspace, supabase);
 await mountImportCenterPage(workspace, supabase);
 await mountMesUserAdminPage(workspace, supabase);
 await mountMesWorkspaceNav(workspace, supabase);
}).catch(reportRemoteFailure);
