import { getMesAuthState } from './integration/auth';
import { mountMesRegistration } from './integration/mesRegistration';
import { mountQualityPage } from './ui/qualityPage';
import { mountMesDashboardPage } from './ui/mesDashboardPage';
import { mountOrdersPage } from './ui/ordersPage';
import { mountEventJournalPage } from './ui/eventJournalPage';
import { mountIntegrityPage } from './ui/integrityPage';
import { mountOperationalWorkflowPage } from './ui/operationalWorkflowPage';
import { mountWorkflowMonitorPage } from './ui/workflowMonitorPage';
import { mountProductionEntryPage } from './ui/productionEntryPage';
import { mountOperatorDowntimePage } from './ui/operatorDowntimePage';
import { mountEquipmentOperationsPage } from './ui/equipmentOperationsPage';
import { mountDispatchGanttPage } from './ui/dispatchGanttPage';
import { mountImportCenterPage } from './ui/importCenterPage';
import { mountMesUserAdminPage } from './ui/mesUserAdminPage';
import { mountMesWorkspaceNav } from './ui/mesWorkspaceNav';
import { mountNsiAdminPage } from './ui/nsiAdminPage';
import { getMesSupabaseClient } from './services/supabase';
const supabase = getMesSupabaseClient();
function reportRemoteFailure(error: unknown): void { window.alert(error instanceof Error ? error.message : 'Серверная операция MES не выполнена'); window.location.reload(); }
void import('./main').then(async () => {
 if (!supabase) return;
 mountMesRegistration(supabase);
 const auth = await getMesAuthState(supabase, { hydrateSnapshot: false }); if (!auth.identity) return;
 const app = document.querySelector<HTMLDivElement>('#app') ?? document.body;
 await mountMesDashboardPage(app, supabase);
 await mountOperationalWorkflowPage(app, supabase);
 await mountProductionEntryPage(app, supabase);
 await mountOperatorDowntimePage(app, supabase);
 await mountEquipmentOperationsPage(app, supabase);
 await mountDispatchGanttPage(app, supabase);
 await mountOrdersPage(app, supabase);
 await mountQualityPage(app, supabase);
 await mountEventJournalPage(app, supabase);
 await mountIntegrityPage(app, supabase);
 await mountWorkflowMonitorPage(app, supabase);
 await mountNsiAdminPage(app, supabase);
 await mountImportCenterPage(app, supabase);
 await mountMesUserAdminPage(app, supabase);
 await mountMesWorkspaceNav(app, supabase);
}).catch(reportRemoteFailure);
